<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Apply_Draft_Water_Mark</name>
   <tag></tag>
   <elementGuidId>ba817b01-aa87-46cd-b4e3-953fdca4cdec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div/div[@dir='ltr']/div/mat-dialog-container[@role='dialog']/div/div/div/div/div[1]/div[1]/div[2]/div[2]/mat-slide-toggle[1]/div[1]/button[1]/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
