<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Category_Staff_M</name>
   <tag></tag>
   <elementGuidId>556919f6-611f-4647-ab47-449c00fec882</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-1']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-1 > span.mdc-list-item__primary-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>75a533ed-a53b-4491-979b-195854af1b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-list-item__primary-text</value>
      <webElementGuid>3de7b253-18fc-4dc1-a08c-b980652f98c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Staff</value>
      <webElementGuid>9c539724-79dc-4727-ae74-590de3d1c7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-1&quot;)/span[@class=&quot;mdc-list-item__primary-text&quot;]</value>
      <webElementGuid>ebee3e11-6bef-4016-aa11-721d03a78042</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-1']/span</value>
      <webElementGuid>a3bcfad0-2fe7-4470-a83e-765721ebd835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partner'])[1]/following::span[1]</value>
      <webElementGuid>8b405757-7eb3-41bb-9398-bd64f978d317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort'])[1]/following::span[2]</value>
      <webElementGuid>3a2a5160-a352-4014-90f9-ab536ef8a317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Staff']/parent::*</value>
      <webElementGuid>3a7c5d01-00e1-4326-8c85-464df5559f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[2]/span</value>
      <webElementGuid>704d9a3d-5224-459a-ae9a-e0b25c6db83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Staff' or . = 'Staff')]</value>
      <webElementGuid>3b49d13a-a7ba-4c63-84de-8452d3d548d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
