<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Choose Category_Object2nd</name>
   <tag></tag>
   <elementGuidId>c4cc63b8-6206-4342-acfc-7e04f9bbf18f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='mat-select-0']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-mdc-select-arrow-wrapper.ng-tns-c2400438669-28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8667517e-556b-4721-9db5-ea9d0279e588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-select-arrow-wrapper ng-tns-c2400438669-28</value>
      <webElementGuid>67527ab8-4cc8-4c9b-a86f-60dadfc454d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-0&quot;)/div[@class=&quot;mat-mdc-select-trigger ng-tns-c2400438669-28&quot;]/div[@class=&quot;mat-mdc-select-arrow-wrapper ng-tns-c2400438669-28&quot;]</value>
      <webElementGuid>bfbc7779-d1b6-413e-955e-8fb24b782e1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-0']/div/div[2]</value>
      <webElementGuid>b37897b2-dae6-4912-ab99-763745afea36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Category'])[2]/following::div[1]</value>
      <webElementGuid>68e65a30-71b7-48ce-a085-764be9d75ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Category'])[1]/following::div[3]</value>
      <webElementGuid>15553da8-f19e-4bf5-a480-2160f3de9212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member ID'])[1]/preceding::div[7]</value>
      <webElementGuid>e214940e-2c9b-40d4-8ed4-40a485d4cdc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::div[15]</value>
      <webElementGuid>1a730cbb-0fb4-45c7-a463-22cb7da939d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-select/div/div[2]</value>
      <webElementGuid>6bf072ca-6f23-4f48-9648-b33934d039bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
