<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Access Permissions_expand-icon</name>
   <tag></tag>
   <elementGuidId>4e5524e3-a5cf-4bf3-9349-816f6bf228a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Expand All']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.expand-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>872bae1d-8c36-4681-838b-ff7e43a68e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Expand All</value>
      <webElementGuid>ea01f212-93d2-482f-909d-0af88dddea98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/ui-uplift-icons/global/collapse-primary.svg</value>
      <webElementGuid>5c07df65-b4bb-424c-9d72-aae33b647526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>expand-icon</value>
      <webElementGuid>313a4f4f-7ee3-4835-9e85-f9c91c8b6f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dasboard-container layout-dashboard drawer-small&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;dashboard-main&quot;]/app-add-team-member[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;d-flex flex-column w-100 h-100 overflow-hidden ng-star-inserted&quot;]/div[@class=&quot;content-block-main d-flex flex-column flex-nowrap gap-20&quot;]/div[@class=&quot;d-flex flex-row align-items-center justify-content-between w-100 ng-star-inserted&quot;]/button[@class=&quot;button-medium mdc-button mat-mdc-button mdc-button--outlined mat-mdc-outlined-button mat-dark mat-mdc-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mdc-button__label&quot;]/span[@class=&quot;button-label ng-star-inserted&quot;]/img[@class=&quot;expand-icon&quot;]</value>
      <webElementGuid>5219bdeb-c7b4-4457-a5ba-2448703a830f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Expand All']</value>
      <webElementGuid>bbdbffa0-ecea-41b4-8ffb-7d6a1d53c4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/img</value>
      <webElementGuid>fad8b70a-ffa6-4000-96a8-aa947398ecf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Expand All' and @src = '/assets/images/ui-uplift-icons/global/collapse-primary.svg']</value>
      <webElementGuid>583793c4-1942-44ca-877d-5ef48e68e71b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
