<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Reimport_Button</name>
   <tag></tag>
   <elementGuidId>45752ef5-4262-4fb4-b7ac-7cb0fcd92916</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='icon'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button-medium.mdc-button.mat-mdc-button.mdc-button--outlined.mat-mdc-outlined-button.mat-dark.mat-mdc-button-base > span.mdc-button__label > img[alt=&quot;icon&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>50387883-766b-4330-bdb4-11ba827a853b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/ui-uplift-icons/global/import-gray.svg</value>
      <webElementGuid>1cd16527-da42-4cdb-a9ac-9f59670751dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>e11613df-6244-48b5-83f0-aa01c0a52037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dasboard-container layout-dashboard drawer-small&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;dashboard-main&quot;]/app-upload-existing-member[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page-wraper&quot;]/div[@class=&quot;dashboard-main ng-star-inserted&quot;]/div[@class=&quot;page-title-block&quot;]/div[@class=&quot;title-right&quot;]/div[@class=&quot;button-group&quot;]/button[@class=&quot;button-medium mdc-button mat-mdc-button mdc-button--outlined mat-mdc-outlined-button mat-dark mat-mdc-button-base&quot;]/span[@class=&quot;mdc-button__label&quot;]/img[1]</value>
      <webElementGuid>876f67a1-acf0-48f5-b637-956d688e1239</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[2]</value>
      <webElementGuid>31b456ea-6231-4917-aa53-5ea4b5b50842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span[2]/img</value>
      <webElementGuid>15649c97-d18a-4f38-b27e-48fc4e950707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/ui-uplift-icons/global/import-gray.svg' and @alt = 'icon']</value>
      <webElementGuid>df6a22c4-e122-4e92-8600-090b0eb0d390</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
