<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PeriodYear End Date_mdc-icon-button _efc6c7</name>
   <tag></tag>
   <elementGuidId>1885ba4c-1cf5-4d85-b0f1-eec4bd1123be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mdc-icon-button.mat-mdc-icon-button.mat-unthemed.mat-mdc-button-base.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Open calendar&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2d4a540c-89c3-4cfa-9b4e-d4ddbf3a716e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c870e761-b44f-4d62-8440-f87931e2f173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mat-ripple-loader-class-name</name>
      <type>Main</type>
      <value>mat-mdc-button-ripple</value>
      <webElementGuid>116f1c2e-b11c-47d6-ba92-bd54bb5a1a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-icon-button mat-mdc-icon-button mat-unthemed mat-mdc-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>83683499-bfd1-45ec-be13-92e985e7dc2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>9d53f62b-2c33-4152-88a4-ce19b3852d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Open calendar</value>
      <webElementGuid>aaf1675b-61fa-48f9-a3d5-d25fab455575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2540bfa2-ffa6-4412-9959-2adc78f08892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dasboard-container layout-dashboard drawer-small&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;dashboard-main&quot;]/app-create-engagement[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page-wraper client-engagement-info-wrapper right-side-panel-hide&quot;]/div[@class=&quot;content-block-main gap-20&quot;]/div[@class=&quot;client-engagement-info flexbox-column w-100&quot;]/div[@class=&quot;create-eng-outer flex-nowrap&quot;]/div[@class=&quot;e-right-main pb-20&quot;]/div[@class=&quot;right-panel-eng mt-lg-0 mt-4&quot;]/div[@class=&quot;details ng-star-inserted&quot;]/form[@class=&quot;input-fields-group mat-form-group row-items-4 ng-pristine ng-invalid ng-touched&quot;]/mat-form-field[@class=&quot;mat-mdc-form-field mat-form-item fixed-label icon-form-after input-fields-item ng-tns-c1798928316-957 mat-mdc-form-field-type-mat-input mat-mdc-form-field-has-icon-suffix mat-form-field-appearance-fill mat-primary ng-pristine ng-invalid ng-star-inserted mat-form-field-invalid ng-touched mat-form-field-hide-placeholder&quot;]/div[@class=&quot;mat-mdc-text-field-wrapper mdc-text-field ng-tns-c1798928316-957 mdc-text-field--filled mdc-text-field--invalid&quot;]/div[@class=&quot;mat-mdc-form-field-flex ng-tns-c1798928316-957&quot;]/div[@class=&quot;mat-mdc-form-field-icon-suffix ng-tns-c1798928316-957 ng-star-inserted&quot;]/mat-datepicker-toggle[@class=&quot;mat-datepicker-toggle border-start ng-tns-c1798928316-957&quot;]/button[@class=&quot;mdc-icon-button mat-mdc-icon-button mat-unthemed mat-mdc-button-base cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>6aabc340-350a-4c01-8e6f-f3bc4b2758bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>b9ec6d8a-05c1-4b67-91b5-baf9030fcd06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Period/Year End Date'])[1]/following::button[1]</value>
      <webElementGuid>f9fe50ca-819a-4dc1-b596-2a4da0b5fe50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::button[1]</value>
      <webElementGuid>26b36b8f-aca3-48e3-b5ad-608de9fa09aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Budget($)'])[1]/preceding::button[1]</value>
      <webElementGuid>1dcaed00-39d8-41b7-8fde-8610d5ad1a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-datepicker-toggle/button</value>
      <webElementGuid>96c8b177-129b-4d17-91a1-6a9c0f5c1437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>55f3cd2f-f0da-4e78-bfd7-bbeb2cd65ea5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
