<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select a country</name>
   <tag></tag>
   <elementGuidId>ed9c59c8-1900-4db8-9f9c-d0396bd359fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mat-select-value-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>086a2291-cb69-4374-b8b0-0bdf6e00dba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-select-value ng-tns-c2400438669-4</value>
      <webElementGuid>06b5bc32-2489-4e72-998d-59d4e3029e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-1</value>
      <webElementGuid>4b948964-fa87-4899-b982-a10a67ca2396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a country</value>
      <webElementGuid>6a52c97c-dc13-436d-839b-0a4d8a3a0697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-1&quot;)</value>
      <webElementGuid>f853223a-d689-47ee-9366-fc1410893f7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-1']</value>
      <webElementGuid>4360a149-3be3-45f0-be81-3be651050d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-0']/div/div</value>
      <webElementGuid>244e1f90-6143-4402-a457-beb4945547b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a country'])[1]/following::div[2]</value>
      <webElementGuid>255d32a9-44a3-4688-9725-aeacd97ab532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create your account'])[1]/following::div[7]</value>
      <webElementGuid>165b0db1-06c0-431a-9f03-9a2568cd203b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::div[8]</value>
      <webElementGuid>3770c0fa-fb1e-4bdf-9e52-1f3ab8c503e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-select/div/div</value>
      <webElementGuid>7215cae5-1590-4121-93d6-25f5e1276108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-1' and (text() = 'Select a country' or . = 'Select a country')]</value>
      <webElementGuid>49569cac-d4a5-4be2-bbf7-2588a2892cb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
