<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>cbe1ddc3-d713-4a68-973e-ecee7dae19d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dasboard-container layout-dashboard drawer-small&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;left-sidebar side-nav&quot;]/app-side-menu[1]/aside[@class=&quot;left-sidebar&quot;]/mat-list[@class=&quot;mat-mdc-list mat-mdc-list-base mdc-list left-nav&quot;]/mat-list-item[@class=&quot;mat-mdc-list-item mdc-list-item mat-mdc-list-item-single-line mdc-list-item--with-one-line ng-star-inserted&quot;]/span[@class=&quot;mdc-list-item__content&quot;]/span[@class=&quot;mat-mdc-list-item-unscoped-content mdc-list-item__primary-text&quot;]/a[@class=&quot;nav-item&quot;]/span[@class=&quot;nav-icon&quot;]/img[1][count(. | //img[@src = '/assets/images/ui-uplift-icons/global/nav-icons/clients.svg' and @alt = 'Icon']) = count(//img[@src = '/assets/images/ui-uplift-icons/global/nav-icons/clients.svg' and @alt = 'Icon'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tbGrid']/table/tbody/tr/td/button/span[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-mdc-menu-trigger.button-text.ms-3.hover-action-item.mdc-button.mat-mdc-button.mat-unthemed.mat-mdc-button-base.ng-star-inserted.cdk-focused.cdk-mouse-focused > span.mdc-button__label > img[alt=&quot;menu&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;menu&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c8ee6d5d-c4b3-4502-9891-f23b3b090974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/ui-uplift-icons/global/kebab-menu-icon.svg</value>
      <webElementGuid>b3cf15eb-6678-4ce3-bdd8-c3a5d9369428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>212dbad2-6a2e-42ee-98f3-e3cd170b5d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbGrid&quot;)/table[@class=&quot;mat-mdc-table mdc-data-table__table cdk-table m-0 table-countable cell-p-8 hover-action trialBalTable customized-sort post-adjusting-selectedrow-color&quot;]/tbody[@class=&quot;mdc-data-table__content&quot;]/tr[@class=&quot;mat-mdc-row mdc-data-table__row cdk-row ng-star-inserted&quot;]/td[@class=&quot;mat-mdc-cell mdc-data-table__cell cdk-cell position-relative cdk-column-accountactions mat-column-accountactions ng-star-inserted&quot;]/button[@class=&quot;mat-mdc-menu-trigger button-text ms-3 hover-action-item mdc-button mat-mdc-button mat-unthemed mat-mdc-button-base ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mdc-button__label&quot;]/img[1]</value>
      <webElementGuid>b0ed6ee3-d8a0-4022-b81a-d95146366d83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbGrid']/table/tbody/tr/td/button/span[2]/img</value>
      <webElementGuid>ec545113-bf25-47a2-a3e5-82bb250e3d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='menu'])[37]</value>
      <webElementGuid>088ae4c8-0501-4428-92f5-6e13d0c47b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button/span[2]/img</value>
      <webElementGuid>4319b3ae-08b5-4023-9a05-89aab3e33746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/ui-uplift-icons/global/kebab-menu-icon.svg' and @alt = 'menu']</value>
      <webElementGuid>97ca27fd-b357-4c95-a365-457784472b3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
