<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please Specify_mat-mdc-checkbox-2-input</name>
   <tag></tag>
   <elementGuidId>27142cb0-ebf7-4928-a457-58cbcb458f9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-mdc-checkbox-2-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-mdc-checkbox-2-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9b5057b-e1d5-4366-8a64-e1b69e044cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b21c8ed8-be1d-49db-ae56-d05f2515af25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-checkbox__native-control</value>
      <webElementGuid>06386457-17f6-4297-97cf-40d86f00a2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-mdc-checkbox-2-input</value>
      <webElementGuid>c7418ed5-6f55-4fb1-b80f-7d9ee85cb3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2c26d204-7945-439d-924d-511df66f82c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-checkbox-2-input&quot;)</value>
      <webElementGuid>33a23ea5-5e0c-4554-9168-2d5a20683ae2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-mdc-checkbox-2-input']</value>
      <webElementGuid>a8151e1e-31fa-4607-9f66-57b0b5aa2d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='mat-mdc-checkbox-2']/div/div/input</value>
      <webElementGuid>fc1e1044-b62d-435d-8540-577de2cc974f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-checkbox/div/div/input</value>
      <webElementGuid>8e6dd61f-735f-4349-b902-793f9d9f28a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mat-mdc-checkbox-2-input']</value>
      <webElementGuid>b78c1537-1ec2-4738-bfac-0136c52175ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
