<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_mat-input-22</name>
   <tag></tag>
   <elementGuidId>42fc4ea6-ff48-4410-9fbe-e6c775e7b719</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mat-input-15&quot;)[count(. | //input[@type = 'text' and @placeholder = 'Description' and @class = 'mat-mdc-input-element trail-textfield desc-field ng-tns-c1798928316-1444 ng-untouched ng-pristine ng-valid mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored' and @id = 'mat-input-15' and @aria-invalid = 'false' and @aria-required = 'false']) = count(//input[@type = 'text' and @placeholder = 'Description' and @class = 'mat-mdc-input-element trail-textfield desc-field ng-tns-c1798928316-1444 ng-untouched ng-pristine ng-valid mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored' and @id = 'mat-input-15' and @aria-invalid = 'false' and @aria-required = 'false'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-input-15</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-15']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Description&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>caf5ae1d-bd54-4e8c-a72c-dac3d2c2f3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11c916a9-6eed-481e-957f-1a11b81ddee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>8e4f0cdd-5d4d-4151-ac05-9b4178f81df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-input-element trail-textfield desc-field ng-tns-c1798928316-1444 ng-untouched ng-pristine ng-valid mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored</value>
      <webElementGuid>cbeaf9c7-e1f5-48ca-9a28-89934a30e6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-15</value>
      <webElementGuid>408b70fe-21fe-4ecb-9f0f-30a7b495fd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>91654a2b-da55-450d-b370-842d94294bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f63aad74-9fd9-4ee0-8f91-5c23823ee37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-15&quot;)</value>
      <webElementGuid>026c20b0-716a-42be-85d5-c9f01f6d7c58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-15']</value>
      <webElementGuid>aae24699-cd9b-4016-bde8-c6eca6e34b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbGrid']/table/tbody/tr[64]/td[4]/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>c820813f-0642-452b-9feb-a5986949023b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>85a58850-3e21-4a4d-aa2d-4110bca73b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Description' and @id = 'mat-input-22']</value>
      <webElementGuid>4de5f3dc-f5b7-42c7-a16a-52e855f4dc43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
