<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Acc No_elem84</name>
   <tag></tag>
   <elementGuidId>3b5ec8b9-200f-4f51-94a9-1b699a760178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;elem84&quot;)[count(. | //input[@type = 'text' and @placeholder = 'Acc.No' and @class = 'mat-mdc-input-element ng-tns-c1798928316-1025 ng-untouched ng-pristine ng-valid mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored' and @id = 'elem84' and @aria-invalid = 'false' and @aria-required = 'false']) = count(//input[@type = 'text' and @placeholder = 'Acc.No' and @class = 'mat-mdc-input-element ng-tns-c1798928316-1025 ng-untouched ng-pristine ng-valid mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored' and @id = 'elem84' and @aria-invalid = 'false' and @aria-required = 'false'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#elem84</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Acc.No']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Acc.No&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1024a8cd-dfb5-41d2-9845-d99d8cc72b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2bb09bf9-3498-4be1-87ea-316a6be140b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Acc.No</value>
      <webElementGuid>a1b58cad-64a1-4815-a962-088bc9787370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-input-element ng-tns-c1798928316-1025 ng-untouched ng-pristine ng-valid mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored</value>
      <webElementGuid>fc31587f-09ee-406a-94e4-40450faa935f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>elem84</value>
      <webElementGuid>8e58129c-a45c-4132-9403-b5057f00a3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1658525d-6bd8-4473-bd90-b05a96babc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b02d6f45-9b8f-45ee-992f-098b6216ccda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elem84&quot;)</value>
      <webElementGuid>02f7cf02-fe06-4a0b-934b-d2ce554b4499</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@placeholder='Acc.No']</value>
      <webElementGuid>0fef3452-5116-455b-9cad-76ad4c10eaf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbGrid']/table/tbody/tr[85]/td[3]/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>63cbad5d-3c66-4e2e-8417-487e29c44a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>cc9c9b08-104f-4c11-ae2d-10ad6d964fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Acc.No' and @id = 'elem84']</value>
      <webElementGuid>4768c4be-a941-4b85-bdeb-44b345838ebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
