<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_visibility_off</name>
   <tag></tag>
   <elementGuidId>c6da3875-caa4-4bfb-a0dd-00633aa6e230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.pointer.material-icons.mat-ligature-font.mat-icon-no-color.ng-tns-c1798928316-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::mat-icon[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;visibility_off&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>64ce3aff-5c5b-4594-b072-0b80017b08b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>403e0983-a81d-4c52-8c2d-74bdc7a8a217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate pointer material-icons mat-ligature-font mat-icon-no-color ng-tns-c1798928316-2</value>
      <webElementGuid>55d7b144-9116-42e2-96ce-5db6bfd85a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b0a3a340-32aa-48ad-8ef1-3f9659c0e123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>10178327-d085-4556-9b8e-6c6f3a6aeb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>visibility_off </value>
      <webElementGuid>1120e549-7d83-4c3e-bd19-7d56b7f1e6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;user-in-main&quot;]/div[@class=&quot;right-block&quot;]/div[@class=&quot;content-block br-12 bg-white gap-24&quot;]/form[@class=&quot;d-flex flex-column gap-20 ng-star-inserted ng-dirty ng-touched ng-valid&quot;]/mat-form-field[@class=&quot;mat-mdc-form-field fixed-label label-none w-100 icon-form-after ng-tns-c1798928316-2 mat-mdc-form-field-type-mat-input mat-mdc-form-field-label-always-float mat-mdc-form-field-has-icon-suffix mat-form-field-appearance-fill mat-primary ng-star-inserted ng-dirty ng-valid ng-touched&quot;]/div[@class=&quot;mat-mdc-text-field-wrapper mdc-text-field ng-tns-c1798928316-2 mdc-text-field--filled&quot;]/div[@class=&quot;mat-mdc-form-field-flex ng-tns-c1798928316-2&quot;]/div[@class=&quot;mat-mdc-form-field-icon-suffix ng-tns-c1798928316-2 ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon notranslate pointer material-icons mat-ligature-font mat-icon-no-color ng-tns-c1798928316-2&quot;]</value>
      <webElementGuid>b3627dea-a869-4d5b-ac7d-4aacf98d15b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::mat-icon[1]</value>
      <webElementGuid>3d3d42ad-c49f-474b-8645-329211aab6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::mat-icon[1]</value>
      <webElementGuid>2ee11c62-2898-4961-a24d-fed9d471c518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember Me'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>03d4ef16-bfcb-4f25-8ed7-8dcdf8bd6f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>309193bb-8329-4916-bff7-7866cc727a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='visibility_off']/parent::*</value>
      <webElementGuid>4151f2c7-8451-41bd-a131-0ccd5da5df2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-icon</value>
      <webElementGuid>2acae4a2-5942-4667-96b3-41f2eb12aa31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'visibility_off ' or . = 'visibility_off ')]</value>
      <webElementGuid>5127b252-89b2-4ce7-870e-d151c556ec57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
