<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-option_Dec 31, 2022</name>
   <tag></tag>
   <elementGuidId>ccf60067-cc3b-44c6-91dc-05dbc863b59c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-33']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-33</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Dec 31, 2022&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-option</value>
      <webElementGuid>5ebb3dcc-1311-4983-9d4a-c422f0a22555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7b1c5065-f139-482d-be26-1b47dee05b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-option mdc-list-item ng-tns-c2400438669-1338 ng-star-inserted</value>
      <webElementGuid>98e21e0f-ba59-4b0b-830f-f881af73142d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-option-33</value>
      <webElementGuid>d2bafede-7fdb-4ebf-8e27-6669b2fe65aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3bf90f3b-ad4d-4433-becb-a372c1aec5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6d790ecb-6c9e-42cd-b48c-53e3843bbf41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Dec 31, 2022 </value>
      <webElementGuid>04847e51-24dd-4555-8b7d-cc7353dcbe1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-33&quot;)</value>
      <webElementGuid>4374aebb-078d-44cb-8429-5b9b06b46fe4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-33']</value>
      <webElementGuid>cd0e3ec8-102e-4d7f-acbf-33063efa3c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-select-16-panel']/mat-option[2]</value>
      <webElementGuid>6155b09e-c54d-45e6-90ad-dc357e286948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dec 31, 2023'])[2]/following::mat-option[1]</value>
      <webElementGuid>b8652578-751f-42ce-907b-cc78161b6bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clear'])[2]/following::mat-option[2]</value>
      <webElementGuid>cb2ade27-cd2c-4fbf-abeb-8a5a15675dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dec 31, 2021'])[1]/preceding::mat-option[1]</value>
      <webElementGuid>13da50ff-584c-4a4f-9f91-7072c7ddc9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[2]</value>
      <webElementGuid>0467a9fc-d7d6-4824-a6ac-ee6205a8b6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-option[@id = 'mat-option-33' and (text() = ' Dec 31, 2022 ' or . = ' Dec 31, 2022 ')]</value>
      <webElementGuid>d5f2b6c9-cdcc-4a9b-83cd-d6cbc0ef9f4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
