<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Provided Account Descriptions are duplica_4b73e1</name>
   <tag></tag>
   <elementGuidId>406fe0be-d1a8-49ef-aef3-7ec2466b3406</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-mdc-dialog-0']/div/div/div/div[2]/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Provided Account Description's are duplicated in the File&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>35f24fa6-aef1-495b-835b-fe5cb0876277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>6cd38af3-8848-4f33-97c8-9dbad9deea49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Provided Account Description's are duplicated in the File</value>
      <webElementGuid>ecc68948-0f9a-41cb-8ca2-ef1353b56dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-dialog-0&quot;)/div[@class=&quot;mdc-dialog__container&quot;]/div[@class=&quot;mat-mdc-dialog-surface mdc-dialog__surface&quot;]/div[@class=&quot;countable-dialog confirmation-dailog incomplete-trial-balance-dialog ng-star-inserted&quot;]/div[@class=&quot;mat-mdc-dialog-content mdc-dialog__content dialog-body-content&quot;]/p[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>b0053824-1417-41ab-8fc5-ccf3a5a69a6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-mdc-dialog-0']/div/div/div/div[2]/p[2]</value>
      <webElementGuid>b1ccc644-30eb-4e95-891b-b83e6e9acc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[1]/following::p[2]</value>
      <webElementGuid>35186643-ba26-4ffc-829a-069e5cf836e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Errors in the File.'])[1]/following::p[2]</value>
      <webElementGuid>26b775fb-5983-49fb-9a20-52a360e58e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/preceding::p[4]</value>
      <webElementGuid>ef63868b-b849-47e8-8f20-ac42d2097187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>52d934a8-7ef3-469f-a0b3-334a1be57e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = concat(&quot;Provided Account Description&quot; , &quot;'&quot; , &quot;s are duplicated in the File&quot;) or . = concat(&quot;Provided Account Description&quot; , &quot;'&quot; , &quot;s are duplicated in the File&quot;))]</value>
      <webElementGuid>8f6fe4c2-ce8d-40b7-a60e-ace7ab53acfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
