<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TB Description</name>
   <tag></tag>
   <elementGuidId>bc9ee1e9-5a26-4728-87f6-710202aee85a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mat-input-18&quot;)[count(. | //input[@type = 'text' and @placeholder = 'Description' and @class = 'mat-mdc-input-element trail-textfield desc-field ng-tns-c1798928316-1026 ng-untouched ng-pristine ng-valid mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored' and @id = 'mat-input-18' and @aria-invalid = 'false' and @aria-required = 'false']) = count(//input[@type = 'text' and @placeholder = 'Description' and @class = 'mat-mdc-input-element trail-textfield desc-field ng-tns-c1798928316-1026 ng-untouched ng-pristine ng-valid mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored' and @id = 'mat-input-18' and @aria-invalid = 'false' and @aria-required = 'false'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-input-18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Description&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f15b02a-da2b-458d-bcf3-a3d5483c93bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e555bb33-4b36-429a-9fcb-5ecb71ee5412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>4cdab5db-2d37-46a6-8f0a-bdf1cd110be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-input-element trail-textfield desc-field ng-tns-c1798928316-1026 ng-untouched ng-pristine ng-valid mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored</value>
      <webElementGuid>faa8aec7-f625-4a83-a851-c995ba49dd30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-18</value>
      <webElementGuid>e1868203-9296-4909-b210-baa4c0d30f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1688ba11-9131-4be0-ac2c-dadbbbb8f802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a1680c5b-1216-4512-b131-97b4e23efd50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-18&quot;)</value>
      <webElementGuid>40b80bed-16c3-417a-97fc-262e19d02d3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@placeholder='Description']</value>
      <webElementGuid>c2be61f8-5441-48f7-a6f8-6e1f3429b9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbGrid']/table/tbody/tr[85]/td[4]/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>77957047-ea2c-4fe9-b0f9-d3e7e8fa54cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>df42c5d8-2cab-40c5-b2a9-01951066b704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Description' and @id = 'mat-input-18']</value>
      <webElementGuid>87646e90-d3e9-4454-a5c7-aa7f9ac6cda1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
