<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Letters</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ffa17b41-14d6-4b7e-8442-226b462b6f2e</testSuiteGuid>
   <testCaseLink>
      <guid>872d3cc4-511b-45f7-9f7b-a2f3135517d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/1-Templates-MasterLetterNames</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ed1a256-9a18-40a4-9d1c-29995f50220c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8360b2a-168c-461b-b44b-d8d747be93f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee5619a9-76d0-405b-9ab4-efc44881f6d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/2-Templates-Com-MasterToFirm</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>107b08c3-ea95-417b-8ebe-225cc0465798</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37002979-e5d4-4b91-87cd-a8b4668976df</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>51ce0f22-bf1a-4bb4-99ba-5ce1f528304d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/3-Templates-VerifyCom-EL and Mgmt Letter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d94e3651-8bda-425b-944e-2ff6d62dee7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa7f0ddf-15cb-4c6d-87f2-db484335ef14</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d6c4b391-6704-4248-ab53-7a5c90d1ce1b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/3.1-Templates-Com-FirmTemplate-Kebab-Duplicate-ExistingAndNew</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60e784a7-acce-4ac7-a4b5-b3ccd54d7312</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6054c26-b71b-4217-bcf5-66a02f018efb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>edd493a4-2aec-48e3-90e3-df11be026b5b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/3.2-Templates-Com-FirmTemplate-Kebab-Rename</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c5547a3-8378-4958-beb9-7e762c7069a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d1c97e1-e00f-4782-aca2-a550b993b29a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>964eb88a-4117-4c93-b976-1c7e07411d43</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/3.3-Templates-Com-FirmTemplate-Kebab-Move</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5db1ecb2-691a-430e-baba-6cdcc6ad7f34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42cecbeb-67a2-45e6-bb88-0463a76374b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a299ede-7d92-4966-b800-ab79db22f557</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/3.4-Templates-Com-FirmTemplate-Kebab-Delete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd3752e5-25a5-420f-94bd-cf84df64fe95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88baf435-f000-434d-bf98-63422d7e9b9f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0c4c82d8-e237-4101-b2b8-25694b76cfe6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/3.5-Templates-Com-FirmTemplate-Folder-Kebab-Rename,Delete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1e76a66-21b4-4548-870e-1617cc0ad3b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5240ad6-0c40-418a-ae39-8f208b856846</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b622c5b-74e0-454c-8e02-d357be161747</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/4-Templates-Com-FirmTemplate-Blank Letter Template</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba175d72-ba4a-40cc-b1c5-2cc8abdc2c69</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc76dda5-3b0c-4769-9dc9-4f2be08a4975</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/4.1-Templates-Com-FirmTemplate-Verify Blank Letter Template</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99f7c509-2a95-4b17-8936-a45cef0ef2f5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29d9260c-4ecd-4aa1-a3d6-1f770f7eaa88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/5-Templates-FirmTemplates-RHS-delete, Duplicate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>992ce591-501d-455c-ae74-3387c7bba659</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81d65fec-a6fc-4fae-b7e4-342bae334060</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/6-Templates-FirmTemplates-RHS-Edit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1311f256-4554-4afb-83cd-03f27ba0068e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8277922-425a-4fbe-a056-184873774f1b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/6.1-Templates-FirmTemplates-RHS-Sections-Checkbox</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbc2b408-b564-4b85-b4fd-3e69816389a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f5e941f-8407-4a36-8b28-64eae304c434</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>063b20e7-ffb7-43b1-a16e-efea36e77153</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/6.2-Templates-FirmTemplates-RHS-Sections-Buttons</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>811faefb-7515-4b81-a90b-b4c8c0ab00ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ec53bb3-88e4-4ec3-89b8-decf14b0f883</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b22c2c2-6b99-430c-a9b5-074a498afc5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>179a5e85-0c08-4eaf-ad76-cce545510b6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae96bfbb-0a11-4dca-b9ff-40ad89960dfc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>edde78ee-839e-4cfe-be46-06aec23e0178</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/6.3-Templates-FirmTemplates-RHS-Edit in Middle Section</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9ad0794-1a5b-47df-be29-087cb73d9d82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c06b722-9dd4-4382-ac27-d87b00fac928</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1086a9ff-2e94-4f5a-9d62-4342b2dfeb1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2e6c24d-0ed7-4957-86be-62f35a7c4d75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3095d824-36da-47ad-b3eb-a37e8ccc313f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5c34e92-e437-4411-a502-cea272eea800</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64030092-1287-447a-876f-457fa35c3c9c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/6.4-Templates-FirmTemplates-VerifyEditedLetter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f5558b7-4d88-4d4a-8cdd-ae083a0f374e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b036157-280d-4400-8b65-f57c7c67f510</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e33c0d78-ff23-4c19-9296-ddc9175996bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd375baf-498f-43e8-b552-4485a773dc2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>912894d4-a406-4b6c-9604-c543a9e86dc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1aa2e9c-7cc2-4412-a84e-6a7cfea71434</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9df90cc-2c35-4d81-a24b-23d85d45e42a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/6.5-Templates-FirmTemplates-Add New Section-AddAllElements</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>830af0a8-3431-4945-ba5c-b06c86043532</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc8dc26c-6b03-4a18-90df-843252a2e7c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70257d5c-f552-46d7-ba0e-505706808e90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18d669b2-2c62-4d4f-9a98-9dd00713d70e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>840ac920-cd3b-42a7-8969-1555f1657231</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcaf00cd-78ef-4d35-8fda-a787e455374b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>842b2cd6-6441-41d4-8dae-c1278a12770d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2854a83a-d16a-4910-a5c2-dc8249ba232b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/8-CreateEngagement-Canada-ClientAdding</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f32eda3b-31e3-4a1c-8b64-8754d1272a62</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9389f68f-ae9f-4ff0-ada0-fb518d0e53f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dff2b824-0f8a-470f-85af-7ccc071bd8f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/8.1-CreateEngagement-Canada-Engagement-COM</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddfadf6f-1680-4c95-877c-47cf074213a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0772a3b7-38c3-4e6f-abe3-3d4bae732aab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0fca2d1-c69d-4439-bcf2-d8a4cee4027a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03231f63-4e90-4c75-b27d-8f6a507edc94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Letters/Letter Templates/8.2-CreateEngagement-Canada-Engagement-REV</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf16ed4c-f568-4b0d-9e00-dfc541626b60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d43968c7-2519-46bd-845f-3e989c0d28d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6cbcbe4-2d0a-411e-b6df-d6d323ad0b96</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
