<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Re-enter Password_mat-mdc-checkbox-1-input</name>
   <tag></tag>
   <elementGuidId>f0bcec76-1d40-49ee-bd6d-6895cbb4480b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-mdc-checkbox-1-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-mdc-checkbox-1-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac680335-86b6-449f-9f62-f77b70ac2e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cfdc2913-6a6c-41d7-8dbf-09d2c4f91e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-checkbox__native-control</value>
      <webElementGuid>c7b88ef9-33b1-4422-8f0b-515ae03a7c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-mdc-checkbox-1-input</value>
      <webElementGuid>fe81ee27-e336-4761-b1d2-abf775bb79bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>448d1eb6-da0d-4c20-b3b2-1fc1293c635d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-checkbox-1-input&quot;)</value>
      <webElementGuid>b3dedcbe-1212-4fa6-a61d-775e81e672e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-mdc-checkbox-1-input']</value>
      <webElementGuid>f4b6b11c-d769-486a-a735-b953b99a4c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='mat-mdc-checkbox-1']/div/div/input</value>
      <webElementGuid>84620f08-f3fc-4cd6-9846-670bd8bf9f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-checkbox/div/div/input</value>
      <webElementGuid>840e194d-6661-4e9e-b3a8-931a3c0f5995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mat-mdc-checkbox-1-input']</value>
      <webElementGuid>d78c1d04-7ef6-4479-bdac-52acdf7a7f3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
