<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ignore</name>
   <tag></tag>
   <elementGuidId>f48ff140-082e-44bf-908c-9c52c03b8f63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[class='button-medium mdc-button mat-mdc-button mdc-button--outlined mat-mdc-outlined-button mat-dark mat-mdc-button-base'] span[class='mdc-button__label']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[normalize-space()='Ignore']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ec4b15fb-c3ef-4352-9b33-f0a53f6381f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-button__label</value>
      <webElementGuid>c0a6dff1-cb30-4bb0-8cfc-a6a9143b84bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ignore </value>
      <webElementGuid>81afc5d9-43a5-4606-b47e-c86c2fddea41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dasboard-container layout-dashboard drawer-small&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;dashboard-main dashboard-page&quot;]/app-teammembersdashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;flexbox-column gap-0 p-24 ng-star-inserted&quot;]/div[@class=&quot;toast-container static-toast w-100&quot;]/div[@class=&quot;ngx-toastr toast-primary w-100 gap-12&quot;]/div[@class=&quot;toast-message flexbox-column gap-8&quot;]/div[@class=&quot;flexbox-row justify-content-end&quot;]/button[@class=&quot;button-medium mdc-button mat-mdc-button mdc-button--outlined mat-mdc-outlined-button mat-dark mat-mdc-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mdc-button__label&quot;]</value>
      <webElementGuid>8918efc3-4787-4ff4-9bbe-08daafa99a3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suraj Agnihotry'])[2]/following::span[7]</value>
      <webElementGuid>f3c3d396-d9ff-4bf1-967d-68defe6fb279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SA'])[2]/following::span[8]</value>
      <webElementGuid>e60c139d-3d27-4649-bcb4-5731b21869e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/preceding::span[9]</value>
      <webElementGuid>a126359c-2361-43dc-9f7c-c2d128213d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ignore']/parent::*</value>
      <webElementGuid>489bcbf9-3647-4897-8efc-b5150bd65b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[normalize-space()='Ignore']</value>
      <webElementGuid>f87b6b34-20dd-45a6-84e5-c45c7d8ecd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Ignore ' or . = ' Ignore ')]</value>
      <webElementGuid>564cd875-b5b9-4591-aa71-6d73f8f4c620</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
