<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Corporation</name>
   <tag></tag>
   <elementGuidId>63efe363-d610-4584-bf1f-d36635eef6c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a8b774c20dd3-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@title='Corporation']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;a8b774c20dd3-0&quot;)[count(. | //div[@class = 'ng-option ng-option-marked ng-star-inserted' and @role = 'option' and @aria-selected = 'false' and @id = 'a8b774c20dd3-0' and (text() = 'Corporation' or . = 'Corporation')]) = count(//div[@class = 'ng-option ng-option-marked ng-star-inserted' and @role = 'option' and @aria-selected = 'false' and @id = 'a8b774c20dd3-0' and (text() = 'Corporation' or . = 'Corporation')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Corporation&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5fcdea2-11cd-4fa2-81bc-d40d553dd9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked ng-star-inserted</value>
      <webElementGuid>768fdc63-885f-4b52-aec0-57f2d0154f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>323b5698-0692-4a48-b05c-20f9c26d4733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>543c7eca-a238-404c-9aa0-8d6ff403a7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a8b774c20dd3-0</value>
      <webElementGuid>3e4e4370-abae-4fe8-9126-28f7b442a4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Corporation</value>
      <webElementGuid>b8546892-e53d-41b7-b3dd-1641aa20b5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a8b774c20dd3-0&quot;)</value>
      <webElementGuid>7d3edd83-1bef-487f-aff0-58c84e219fd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@title='Corporation']</value>
      <webElementGuid>17563aaf-a621-464b-a372-73e47f53b9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a8b774c20dd3']/div/div[2]/div</value>
      <webElementGuid>13b3bea9-733c-48e1-99a5-fbdcb43c037d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[5]</value>
      <webElementGuid>2a573802-b215-4638-9d17-7e16514de9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>a10e7c61-0da6-4a93-a219-5bcce3b4ac54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a8b774c20dd3-0' and (text() = 'Corporation' or . = 'Corporation')]</value>
      <webElementGuid>d69ff827-07a7-463e-a4a9-01566fabeca3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
