<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InviteSent_VerifyStatus_MyClient</name>
   <tag></tag>
   <elementGuidId>416caa82-890e-4f1f-aabd-281c9530e91d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/app-root[1]/app-dashboard[1]/div[1]/div[1]/div[2]/app-client[1]/div[1]/div[1]/div[2]/div[2]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[5]/p[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
