<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inviteEmail</name>
   <tag></tag>
   <elementGuidId>d6457184-c1cb-4de0-8d54-eb94f66ab93f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody/tr[3]/td[14]/div[1]/button[1]/span[2]/img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>4516e6ba-dec1-4f05-893c-25090a557121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1716142939538</value>
      <webElementGuid>b004c230-c28a-4846-91d9-1e6838f33757</webElementGuid>
   </webElementProperties>
</WebElementEntity>
