<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_preview-select</name>
   <tag></tag>
   <elementGuidId>abd6b535-d426-4ae7-a48d-9b7527338ea2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='preview-select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#preview-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>40d5b746-dc3b-4eb3-9a6a-b5f0c66ca83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preview-select</value>
      <webElementGuid>d9023afd-ebad-4608-8535-79db4d23cef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>12b691a8-1dd8-454a-98c2-075b20de7a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Use select tool</value>
      <webElementGuid>eefef75b-ded6-464a-a93d-7de9e1d9b54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8019168a-9b42-40b6-b8da-570c7b8fd55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>spectrum-ActionButton spectrum-ActionButton--quiet</value>
      <webElementGuid>be28acf6-bec0-4f33-8d81-8e5af5036b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preview-select&quot;)</value>
      <webElementGuid>526d286a-f9cb-4eb2-a1ee-96b191a2f7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DraganddropObj/iframe_Close edit mode_iframe-pdf_div</value>
      <webElementGuid>9fa56188-4991-40d1-9c91-63d7aab26183</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='preview-select']</value>
      <webElementGuid>0ee956a2-f180-4cb0-a8d8-5f65229f3bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quick-tools-view']/ul/li/div/div/div/button</value>
      <webElementGuid>93d7e8b0-352f-4d61-a87a-5ca78ed4e392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::button[3]</value>
      <webElementGuid>7e7b1096-e1f7-4c7f-8c20-b0cfbc0b2fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 1'])[1]/preceding::button[4]</value>
      <webElementGuid>76a7bbba-d649-4d0f-9a0a-af8f9807a1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test entity'])[1]/preceding::button[4]</value>
      <webElementGuid>4a8b11f5-dfba-40f6-9285-beb663d99c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/button</value>
      <webElementGuid>1298cc92-5e38-4319-8bba-c52b81b5bf39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'preview-select']</value>
      <webElementGuid>2886d9f9-01ae-44cd-b1ab-6c729c5de3ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
