<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>4bc673fe-0b8a-408a-a667-5d22119ac464</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='adobe-dc-view']/div/div/div/div/div/button[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.spectrum-Button.spectrum-Button--primary.sdk-SaveActionView-save</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Save' or . = 'Save')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5dbf99ed-b98f-4d87-be3f-516432be57cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>spectrum-Button spectrum-Button--primary sdk-SaveActionView-save</value>
      <webElementGuid>70ca00b3-98c8-44c3-bd94-dd3a5858e1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>53fe65e7-922e-4cb4-9819-49ea2e8c5dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adobe-dc-view&quot;)/div[@class=&quot;JuTe6q_spectrum _5QszkG_spectrum _5QszkG_i18nFontFamily PFjRbG_spectrum--light xSyFOq_spectrum--medium zA6MfG_spectrum zA6MfG_spectrum--dark zA6MfG_spectrum--darkest zA6MfG_spectrum--large zA6MfG_spectrum--light zA6MfG_spectrum--lightest zA6MfG_spectrum--medium&quot;]/div[@class=&quot;react-spectrum-provider spectrum spectrum--light spectrum--medium&quot;]/div[@class=&quot;MainApp__app___d1GrX&quot;]/div[1]/div[@class=&quot;sdk-HeaderView-header sdk-HeaderView-header-modernViewer&quot;]/button[@class=&quot;spectrum-Button spectrum-Button--primary sdk-SaveActionView-save&quot;]</value>
      <webElementGuid>22336586-1afc-460e-bd3f-3ec84f336344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DraganddropObj/testXlsxedit/iframe_Close edit mode_iframe-pdf_div (1)</value>
      <webElementGuid>8f18b8af-702c-4b65-b097-20b29ef185fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adobe-dc-view']/div/div/div/div/div/button[3]</value>
      <webElementGuid>a6615f9d-f4d9-4624-8d2a-3b8eaa443ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 1'])[1]/preceding::button[7]</value>
      <webElementGuid>b95848f4-18f1-473b-9c81-1962c4f0fccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>bc0413b6-64d8-46bd-9780-c5e64e7adb98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>78639568-c9f8-47c4-b7f8-fb1eba8c027d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>ee78f8d2-9c59-4d54-a8bd-78f69942967c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
