<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ColorPicker__colorPickerCircle</name>
   <tag></tag>
   <elementGuidId>57af7909-2bb0-4632-a381-1fcdb6bd2bfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>circle.ColorPicker__colorPickerCircle___qlLdn</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;react-spectrum-47&quot;)/div[@class=&quot;ContextMenuHeader__ContextMenuHeaderWrapper___1Ld29 ContextMenuHeader__noBody___2bM0r&quot;]/div[2]/div[1]/li[@class=&quot;spectrum-Menu-item ContextMenuHeader__ContextMenuHeaderButton___1wTDl&quot;]/svg[1]/circle[@class=&quot;ColorPicker__colorPickerCircle___qlLdn&quot;][count(. | //*[@ref_element = 'Object Repository/DraganddropObj/iframe_Close edit mode_iframe-pdf_div (1)']) = count(//*[@ref_element = 'Object Repository/DraganddropObj/iframe_Close edit mode_iframe-pdf_div (1)'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>41198bd5-06a1-4d1c-8491-a94451817561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e54606f8-8712-4bc3-ab01-d4a568902d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>b7c85e0e-c608-4019-99da-937d3a43e7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>101650d2-2953-4a39-ae7b-b162af902acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgb(255, 255, 255)</value>
      <webElementGuid>5de278be-eefd-46df-905c-c92c3c506119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ColorPicker__colorPickerCircle___qlLdn</value>
      <webElementGuid>24f0a920-6915-46ab-9b54-b2d5da8aa34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-spectrum-47&quot;)/div[@class=&quot;ContextMenuHeader__ContextMenuHeaderWrapper___1Ld29 ContextMenuHeader__noBody___2bM0r&quot;]/div[2]/div[1]/li[@class=&quot;spectrum-Menu-item ContextMenuHeader__ContextMenuHeaderButton___1wTDl&quot;]/svg[1]/circle[@class=&quot;ColorPicker__colorPickerCircle___qlLdn&quot;]</value>
      <webElementGuid>55bbe193-e02d-4f2a-8657-e8c5b1d46489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DraganddropObj/testXlsxedit/iframe_Close edit mode_iframe-pdf_div (1)</value>
      <webElementGuid>038f0812-ce7f-491d-a649-9ed8c14fc371</webElementGuid>
   </webElementProperties>
</WebElementEntity>
