<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Close edit mode_iframe-pdf_div</name>
   <tag></tag>
   <elementGuidId>0282182d-2173-409c-b3d6-d6c86bfc3b0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframe-pdf_div']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframe-pdf_div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4ce4c617-ece4-49c2-93a1-b8beea727110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://documentservices.adobe.com/view-sdk/3.27.1_3.2.4-b4b0ecd5/iframe.html?locale=en-US&amp;msi=11210010295100105118&amp;parent=https%3A%2F%2Fuat.adinovis.com%2Ffile-preview%2Fpdf%2Ffalse%2F8dfe5a29-78e9-4864-b5c8-9e05837466ef%2Fedit</value>
      <webElementGuid>f0420912-c44f-4447-8c6e-df38732b7a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframe-pdf_div</value>
      <webElementGuid>ab428132-d7a3-49dd-8eeb-c718d95690f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>allowfullscreen</value>
      <webElementGuid>08f9a078-f321-41cc-81f0-3371619726ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PDF Embed API</value>
      <webElementGuid>96a6c262-185f-4a61-b238-4d31cd096d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframe-pdf_div&quot;)</value>
      <webElementGuid>f4f4a3d7-aa1d-4310-bffd-1a24cd1276c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframe-pdf_div']</value>
      <webElementGuid>6aed4aad-90e0-4841-961c-5ef8db7ff9c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdf_div']/iframe</value>
      <webElementGuid>7b3471a4-2f42-4d64-b5b7-91b20af4ba22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ba1137fd-b5f6-4058-b2be-d0f84b41b913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://documentservices.adobe.com/view-sdk/3.27.1_3.2.4-b4b0ecd5/iframe.html?locale=en-US&amp;msi=11210010295100105118&amp;parent=https%3A%2F%2Fuat.adinovis.com%2Ffile-preview%2Fpdf%2Ffalse%2F8dfe5a29-78e9-4864-b5c8-9e05837466ef%2Fedit' and @id = 'iframe-pdf_div' and @title = 'PDF Embed API']</value>
      <webElementGuid>13bb68cb-f9b1-439a-bdb0-a6765ab6dc09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
