<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectYellowColour</name>
   <tag></tag>
   <elementGuidId>45b047e9-41fc-4ba3-9dae-4b73b2732272</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='react-spectrum-54']/div/div[2]/span[3]/div/span/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[title=&quot;Yellow&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>132cb0b7-aa0b-4d99-ac09-5495c5204469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Yellow</value>
      <webElementGuid>2814eddf-2b8e-4939-9e6c-bf85c893ce86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>376f8604-bea9-4a90-8bfd-99b13a96caf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>772e7039-b6c8-4408-ae41-28e82272c78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-spectrum-54&quot;)/div[@class=&quot;ColorPicker__colorPickerContainer___wEzoC ColorPicker__focusedRingContainer___HqGGP&quot;]/div[@class=&quot;github-picker ColorPicker__colorPicker___dKcLr&quot;]/span[3]/div[1]/span[1]/div[1]</value>
      <webElementGuid>34e7699f-01cf-4d4a-af0f-b3e0d5f8b2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DraganddropObj/testXlsxedit/iframe_Close edit mode_iframe-pdf_div (1)</value>
      <webElementGuid>03a4db4c-e561-4bc6-adad-c75e718edd3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='react-spectrum-54']/div/div[2]/span[3]/div/span/div</value>
      <webElementGuid>a42560dd-f8a9-4c21-80a4-c15578c48dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/div/span/div</value>
      <webElementGuid>1a32fb34-29b0-47ab-969b-49251a42db61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Yellow']</value>
      <webElementGuid>9af36524-ab19-49f8-8ac1-986e66009ed6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
