<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectRedColour</name>
   <tag></tag>
   <elementGuidId>d27a3871-2056-4e91-83f4-612f005c527a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='react-spectrum-54']/div/div[2]/span[3]/div/span/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[title=&quot;Red&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5c98c472-cc12-415e-978f-f72852a65630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Yellow</value>
      <webElementGuid>cf8dc0ed-b32b-4202-9f64-e6a05bf734b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>53dd8672-33da-4992-bbbe-609dbd6db683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>fcd6590d-606b-4980-a24d-83d65cb68552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-spectrum-54&quot;)/div[@class=&quot;ColorPicker__colorPickerContainer___wEzoC ColorPicker__focusedRingContainer___HqGGP&quot;]/div[@class=&quot;github-picker ColorPicker__colorPicker___dKcLr&quot;]/span[3]/div[1]/span[1]/div[1]</value>
      <webElementGuid>d20b75b0-68fb-4c99-9c32-eae647d56225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DraganddropObj/testXlsxedit/iframe_Close edit mode_iframe-pdf_div (1)</value>
      <webElementGuid>db010319-c3ff-4be9-a381-2f9ddb0e091c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='react-spectrum-54']/div/div[2]/span[3]/div/span/div</value>
      <webElementGuid>3c113849-7f3d-4135-b4d6-cf36d8296c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/div/span/div</value>
      <webElementGuid>3bd29486-398a-404c-957a-0215d700890b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Yellow']</value>
      <webElementGuid>fc8048b7-d2d7-461a-a631-6d9ec5d30237</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
