<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Source TC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>7d573bc1-9365-4a1d-99ae-8a015d5cbd32</testSuiteGuid>
   <testCaseLink>
      <guid>1e275a3c-2faa-469a-ba5a-d290a282788c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/0.1-ClientAdding - UAT</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dda13c80-4c93-4aa7-a54c-ba72c531a68f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bdf2864-2c4a-40cd-95f4-9d8087f481b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03d1bcba-db59-4e09-b135-78fe38ef5ed0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/1-XeroIntegrationFlow</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b409bfbe-d0f3-4b73-9312-5299abdd7904</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ece9aebb-2a5b-4a6f-b4ac-822f0dfdf4b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/2-EngagementCreation UAT</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddfadf6f-1680-4c95-877c-47cf074213a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0772a3b7-38c3-4e6f-abe3-3d4bae732aab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b3c91a2-dc0f-4438-954a-70e0cb32e383</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/3-CheckTBLoaded</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e50b0fd3-cf2c-4e1e-8862-95ee88a23ba0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>36243e0c-d7ad-480e-943d-3a9313668ed3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/4.CheckRefreshButtonEnabled</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d13c78c5-6aad-47f9-b8cc-1e55b016a0bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00504ee2-51ee-4607-9dd1-4ddedf763dcb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/5.TBSearchField</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa033599-5c10-4125-92c1-70087531db5e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c342d624-cf8d-4e76-98d7-9dab520d58ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/6.TBSource-TBExport</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbc9d231-38c4-4837-bbff-116de90547f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92e3e6a4-94e9-4709-88c3-c866cc26e54c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/9-SourceTBBalanceOutCheck</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a004caab-444d-48e7-9b56-5c0df0b5b135</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c01b5843-e2fb-4bb4-a453-861ae8f2e416</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/11-SourceKebabMenu-Add</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1278318d-9478-4c7c-8eed-2b06192a677e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea6486c6-4aa5-436d-aa02-d35080644acd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/12-SourceKebabMenu-Edit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>100255f6-1ad8-499f-9bee-c1767b651d5d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>63f608db-c04c-40f5-8b4a-8be67dfcfed3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/13-SourceKebabMenu-Delete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>028352ce-f302-40ac-871a-d7bdcfb03fc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0262658a-de70-469e-ae50-ae02a1df362d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/14-SourceKebabMenu-Duplicate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36c45647-fe97-4ff5-908e-5b1d8ef91488</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c46ecda3-8e42-4c43-9ba3-c755601c4328</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/15.1-SourceKebabMenu-UpdateToSource-HappyFlow</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>07d0030b-610a-40f8-a33d-f98d42f61c97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/15.2-UpdateToSourceAccountPopupVerification</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf96d138-9369-4496-914a-65457014903f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00df60ee-af1a-491c-9750-d70d5ff9a5ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/16.1-InsideEngagementXeroLogo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd853950-95d8-49ea-b660-cd0beb27883a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3cb5c2f5-f159-41f7-8d38-18fad8bc1237</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/16.2-DeleteUpdateToSourceAccount</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c0af83b-4107-4d60-8d57-8187e82488f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>21ac7187-e539-428f-8e27-cba500957e97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/17.1-SourceKebabMenu-AddToSource-HappyFlow</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bc8febc-e48e-4570-ae92-adc81bbddee3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1c687c5-bb0a-4d5a-b96c-aea2242c24b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/17.3-AddToSourceAccountPopupVerification</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af0c7a41-4030-425c-ac94-3242b293ef32</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11ba3036-7e11-45a4-97d1-c77021ab149a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/18.1-AdjEntryCashAccount</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>517695e0-f3ab-45d8-b47c-6728cd5edba1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a9e680f-ae31-414d-b79e-63b137add45d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/18.2-AdjEntry-EditCashAdjEntry</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edb2ab3a-b5b8-4ca8-a5f6-6234ec503589</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6082beb0-881c-4263-85b0-ef14227d8dc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/18.3-AdjEntryCashAccountValidateRestriction</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>370706ac-ba6a-4341-a8fa-9146a41560fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd53fd3d-9e5c-48bf-aaa3-e8311a1be561</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/18.4-AdjEntryRestrictedAccount</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e4af5fb-8431-4a56-b687-a991ea11aac6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dcee0270-8e50-4a3b-b7a3-804dab616256</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/18.5-AdjEntryValidateRestrictedAccount</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3841439c-0fb9-4a3b-b44e-670561b402ce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb9fbce2-c7a4-4b63-b1b6-32b62f34edef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TB/Source Flow/18.6-AdjEntry-VerifyStatusOnRHSTopSide</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3053c13-14c5-4516-b77f-925e84e1f099</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
