<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddClient_Button</name>
   <tag></tag>
   <elementGuidId>f2b4b0d0-9474-4300-92a1-672fc2e856ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@src='/assets/images/ui-uplift-icons/global/down-arrow-white.svg']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@src='/assets/images/ui-uplift-icons/global/down-arrow-white.svg']</value>
      <webElementGuid>539da5bb-c379-4640-ae06-261833dc872a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
