<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dashboard_Client_Option</name>
   <tag></tag>
   <elementGuidId>088f6ade-62e8-43b0-b3ed-70d9b59515af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@src='/assets/images/ui-uplift-icons/global/nav-icons/clients.svg']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@src='/assets/images/ui-uplift-icons/global/nav-icons/clients.svg']</value>
      <webElementGuid>715ac8ec-6cba-4d0c-a632-898d31849b51</webElementGuid>
   </webElementProperties>
</WebElementEntity>
