<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Engagement_COM-UAT-Dec312021</name>
   <tag></tag>
   <elementGuidId>af09ce71-3730-4cc0-8376-e672d46b5976</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/following::span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.text-button.mdc-button.mat-mdc-button.ng-tns-c3270910167-1173.mat-unthemed.mat-mdc-button-base.ng-star-inserted > span.mdc-button__label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0de43a87-f6a9-43bc-9ce1-707dfec99736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-button__label</value>
      <webElementGuid>929d95f9-2b29-48d5-a996-3e6721fcdd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COM-UAT-Dec312021</value>
      <webElementGuid>a76ca748-7bf2-43a0-a5a9-196f01670a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dasboard-container layout-dashboard drawer-small&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;dashboard-main&quot;]/engagements-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page-wraper&quot;]/div[@class=&quot;content-block-main gap-20&quot;]/engagements-list-grid[@class=&quot;ng-tns-c3270910167-1173 ng-star-inserted&quot;]/div[@class=&quot;horizontal-items h-100 ng-tns-c3270910167-1173&quot;]/div[@class=&quot;card table-responsive ng-tns-c3270910167-1173 ng-star-inserted&quot;]/table[@class=&quot;mat-mdc-table mdc-data-table__table cdk-table mat-sort table-countable template-edit-table ng-tns-c3270910167-1173 ng-star-inserted&quot;]/tbody[@class=&quot;mdc-data-table__content&quot;]/tr[@class=&quot;mat-mdc-row mdc-data-table__row cdk-row expanded-element-row ng-tns-c3270910167-1173 ng-star-inserted&quot;]/td[@class=&quot;mat-mdc-cell mdc-data-table__cell cdk-cell engagment-coltd cdk-column-engagementName mat-column-engagementName ng-tns-c3270910167-1173 ng-star-inserted&quot;]/button[@class=&quot;text-button mdc-button mat-mdc-button ng-tns-c3270910167-1173 mat-unthemed mat-mdc-button-base ng-star-inserted&quot;]/span[@class=&quot;mdc-button__label&quot;]</value>
      <webElementGuid>398fb451-6429-4bb0-90bb-829281e60537</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/following::span[2]</value>
      <webElementGuid>f1c86026-c3b4-4b8e-9bc0-b024bc9db866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Created'])[1]/following::span[2]</value>
      <webElementGuid>1837f3bd-94c7-4fb3-90ef-68de38a07ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dec 31, 2021'])[1]/preceding::span[4]</value>
      <webElementGuid>ff4ca808-b073-4157-936a-eb901d84f574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Assignees'])[1]/preceding::span[6]</value>
      <webElementGuid>f87c15bb-c791-4e7d-b01e-d0f581fbfb81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COM-UAT-Dec312021']/parent::*</value>
      <webElementGuid>c299541e-dee2-49d2-9913-181891a5b1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/button/span[2]</value>
      <webElementGuid>6cbc063a-7ffb-4f35-96a8-19574e8941a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'COM-UAT-Dec312021' or . = 'COM-UAT-Dec312021')]</value>
      <webElementGuid>013f45a4-e89b-4a85-87cc-b668016d64b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
