<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Close edit mode_iframe-pdf_div (1)</name>
   <tag></tag>
   <elementGuidId>da502d30-4b90-41be-b310-5db15247f61e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframe-pdf_div']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframe-pdf_div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>96700c51-e574-477c-b70a-30959d6d0879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://documentservices.adobe.com/view-sdk/3.27.1_3.2.4-b4b0ecd5/iframe.html?locale=en-US&amp;msi=11210010295100105118&amp;parent=https%3A%2F%2Fuat.adinovis.com%2Ffile-preview%2Fpdf%2Ffalse%2Fc1b33b48-6429-4eaa-ab92-deaa2e8ee3e3%2Fedit</value>
      <webElementGuid>db15b378-9a6b-42a6-8f64-45b0eee5d601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframe-pdf_div</value>
      <webElementGuid>82960386-f89f-4cb8-aaf5-5f1402232c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>allowfullscreen</value>
      <webElementGuid>25fa9944-c5c5-4d0b-a40b-75ca7b379c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PDF Embed API</value>
      <webElementGuid>bfb846fa-2e03-4762-b800-eb1464bd70b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframe-pdf_div&quot;)</value>
      <webElementGuid>b11a10b4-2c3c-406b-b321-1284ac3a0124</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframe-pdf_div']</value>
      <webElementGuid>08a6cc36-e14f-4649-b21d-d841545ea80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdf_div']/iframe</value>
      <webElementGuid>8cbbf4df-f152-44d3-ae56-46980f23605e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>9b813802-9e3e-466b-9739-1c6ee09de253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://documentservices.adobe.com/view-sdk/3.27.1_3.2.4-b4b0ecd5/iframe.html?locale=en-US&amp;msi=11210010295100105118&amp;parent=https%3A%2F%2Fuat.adinovis.com%2Ffile-preview%2Fpdf%2Ffalse%2Fc1b33b48-6429-4eaa-ab92-deaa2e8ee3e3%2Fedit' and @id = 'iframe-pdf_div' and @title = 'PDF Embed API']</value>
      <webElementGuid>ab0d08d9-11b4-4f74-b2e3-6d1f3212e9bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
