<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Capture object_frame</name>
   <tag></tag>
   <elementGuidId>6a2d27ee-1283-481f-9dff-65ab5279efed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>22a0fb6a-73a5-4652-af1a-fc3a66a1f609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>62529c45-7eba-47f1-9494-f0a93524957e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>ac4b94fa-820d-49f8-af8b-9db0f8e8c771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>637c93f8-0c7c-4a54-9b51-b48c5af21415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>485ab06e-7dec-4fbb-95dc-60efd67535ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-frame</value>
      <webElementGuid>68202a5c-01d3-4a8d-acb9-023c5ed14f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://FFC-excel.officeapps.live.com/x/_layouts/xlviewerinternal.aspx?ui=en-US&amp;rs=en-US&amp;dchat=false&amp;sc=false&amp;IsLicensedUser=1&amp;wopisrc=https://uat-api.adinovis.com/api-adinovis/v1/wopi/files/4ac7e4bf-c934-4358-87e2-077c20ddd69d?access_token=eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3VhdC1hcGkuYWRpbm92aXMuY29tL2FwaS1hZGlub3ZpcyIsInN1YiI6InVzdWF0dXBkYXRlZDIxLjFAeW9wbWFpbC5jb20iLCJhdWQiOiJodHRwczovL3VhdC5hZGlub3Zpcy5jb20iLCJleHAiOjE3MTU5MzMzNzQsInUiOiIxNjUyOTc2MzI5ODMwOTA0NzMyMiIsImlhdCI6MTcxNTg0Njk3NH0.I_xg9e2sMmMtWFwrxVVh2-IVvfeQ9IC-26zg863yOb4rXwSyajKZwioLtvhmlBQGHgvMktghXcfQAxp_CIjqZAl4z6JjeqC8G9w1OJoEn7g_iDMbQkZ1Cpyl_Pd0aBG9jPQNaZSo6mpsBONYqDZyNTCr6sgMvO8-frBnVL-QrXZItZadcvbVr0gwlrorUlS5U_QVEPLeZ8eY1boqZYHQxjEXd6CePWnI969Ppa1XrgpSm18NwI7h8pA8gW6DdpyFzjU0aKouzo1fg0PdnfdcFCqWLsf-eYyD5z4ytgHZwf8N8So_YcprTh5k4eCjzBFu4n56iipVQh7hx9QrXNRpCQ</value>
      <webElementGuid>48104c87-3f93-4746-ac39-8ed79fa7259e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frame&quot;)</value>
      <webElementGuid>cd478fd9-5b41-4e4b-8740-63af0f194072</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='frame']</value>
      <webElementGuid>8d8b6a67-958c-486d-af20-3d123ee04ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e496f3a8-d91a-4088-87dd-5f5a859cb5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'frame' and @name = 'frame' and @src = 'https://FFC-excel.officeapps.live.com/x/_layouts/xlviewerinternal.aspx?ui=en-US&amp;rs=en-US&amp;dchat=false&amp;sc=false&amp;IsLicensedUser=1&amp;wopisrc=https://uat-api.adinovis.com/api-adinovis/v1/wopi/files/4ac7e4bf-c934-4358-87e2-077c20ddd69d?access_token=eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3VhdC1hcGkuYWRpbm92aXMuY29tL2FwaS1hZGlub3ZpcyIsInN1YiI6InVzdWF0dXBkYXRlZDIxLjFAeW9wbWFpbC5jb20iLCJhdWQiOiJodHRwczovL3VhdC5hZGlub3Zpcy5jb20iLCJleHAiOjE3MTU5MzMzNzQsInUiOiIxNjUyOTc2MzI5ODMwOTA0NzMyMiIsImlhdCI6MTcxNTg0Njk3NH0.I_xg9e2sMmMtWFwrxVVh2-IVvfeQ9IC-26zg863yOb4rXwSyajKZwioLtvhmlBQGHgvMktghXcfQAxp_CIjqZAl4z6JjeqC8G9w1OJoEn7g_iDMbQkZ1Cpyl_Pd0aBG9jPQNaZSo6mpsBONYqDZyNTCr6sgMvO8-frBnVL-QrXZItZadcvbVr0gwlrorUlS5U_QVEPLeZ8eY1boqZYHQxjEXd6CePWnI969Ppa1XrgpSm18NwI7h8pA8gW6DdpyFzjU0aKouzo1fg0PdnfdcFCqWLsf-eYyD5z4ytgHZwf8N8So_YcprTh5k4eCjzBFu4n56iipVQh7hx9QrXNRpCQ']</value>
      <webElementGuid>127488d5-014c-411c-bcf3-87eeab2cf7ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
