<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SearchButton_DocumentRepo</name>
   <tag></tag>
   <elementGuidId>c6a1dab9-2342-486a-9505-7afaf53d5b3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@title='Search']//img[@alt='icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.expand-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>298cdc3f-8e4a-4e57-96a3-7bb971dca61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/ui-uplift-icons/global/search-Icon.svg</value>
      <webElementGuid>856e849d-63ce-44cb-91d4-8e7630580482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>b88e4730-b375-49f8-beb2-624395683182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>expand-img</value>
      <webElementGuid>08b0ae8a-a007-4629-8e1a-f8d8df03a11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-13-0&quot;)/div[@class=&quot;mat-mdc-tab-body-content ng-tns-c2396234108-1366 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;search-filter-block document-content-header gap-12 px-3 py-2 ng-star-inserted&quot;]/button[@class=&quot;button-text mdc-button mat-mdc-button mat-unthemed mat-mdc-button-base&quot;]/span[@class=&quot;mdc-button__label&quot;]/img[@class=&quot;expand-img&quot;]</value>
      <webElementGuid>af6f94b4-1005-4f41-9f22-1f11f27818a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@title='Search']//img[@alt='icon']</value>
      <webElementGuid>a7c7c944-cf0d-474a-94f1-7f1df12d27ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[118]</value>
      <webElementGuid>321fa40a-a9f9-4a39-b3dd-d54d349818f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tab-body/div/div/button[3]/span[2]/img</value>
      <webElementGuid>7d932543-1c0d-4da1-8c32-a5532254deec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/ui-uplift-icons/global/search-Icon.svg' and @alt = 'icon']</value>
      <webElementGuid>10339820-71c8-45d1-b7b7-7d6ffbb3c6f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
