<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_test.xlsx</name>
   <tag></tag>
   <elementGuidId>4f71853f-f0c4-4d42-900b-31a92a436a63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'test.xlsx' or . = 'test.xlsx')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[2]//span[2]//span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(2) span:nth-child(2) span:nth-child(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>069a4775-a334-4023-b61b-49049b05bfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-title</value>
      <webElementGuid>8d5111d5-06bb-4e4b-8b63-31478b3394cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test.xlsx</value>
      <webElementGuid>cf8d2a1c-1eea-47cb-8263-c1034899af95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-drop-list-200&quot;)/li[@class=&quot;cdk-drag list-item-content h-auto py-2 ng-star-inserted&quot;]/span[@class=&quot;path-title-block flex-row&quot;]/span[@class=&quot;item-title&quot;]</value>
      <webElementGuid>0ef4344b-02f7-48aa-9a3f-18ba67afd4e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[2]//span[2]//span[1]</value>
      <webElementGuid>0b9aeae4-5faf-49b7-9245-be1f4e75c50c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/following::span[9]</value>
      <webElementGuid>fa48e8e8-a344-4fa8-92ad-fb99e61b47b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Clients'])[1]/following::span[27]</value>
      <webElementGuid>3ff1ea3d-a4bd-4a50-a1a7-2bf1d675b366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA-1-'])[1]/preceding::span[3]</value>
      <webElementGuid>5488acdf-f9bc-47ff-bed7-adddcdc424bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='s3 retest.xlsx'])[1]/preceding::span[4]</value>
      <webElementGuid>f385dff1-f021-4b2a-838e-72275a331db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test.xlsx']/parent::*</value>
      <webElementGuid>dcb68051-1448-4339-b0f0-6643518c3c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span[2]/span[2]</value>
      <webElementGuid>dc508b86-6b79-4110-a62f-d1ee13376daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'test.xlsx' or . = 'test.xlsx')]</value>
      <webElementGuid>5b95d055-e04b-42ed-a4eb-4f0c8700f0d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
