<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_exceleditprmison_Button</name>
   <tag></tag>
   <elementGuidId>90b932b6-e672-47dc-b54a-7336bf73e675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Viewing'])[2]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fui-MenuButton__menuIcon.___1tl8qtt.fp4gqsa.f1ugzwwg.fvblgha.frx94fk.fbyavb5.f1r9easw.f1n5fo7a.f1v0hrxw > i.root-89 > svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>26768798-cc12-4ee2-80da-8c161da3746f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>f2092c62-163e-4e8a-937a-c81ab27390b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>ad5ea888-d3a3-4df5-bdd5-8f2036a7867f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0,0,2048,2048</value>
      <webElementGuid>43a6ee56-4723-4652-8862-0f33bd6023a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>536ea6d6-b02c-46ec-87b4-e84a82ed9ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ModeSwitcher-container&quot;)/button[@id=&quot;ModeSwitcher&quot;]/span[@class=&quot;fui-MenuButton__menuIcon ___1tl8qtt fp4gqsa f1ugzwwg fvblgha frx94fk fbyavb5 f1r9easw f1n5fo7a f1v0hrxw&quot;]/i[@class=&quot;root-89&quot;]/svg[1]</value>
      <webElementGuid>b83bd68b-c9d4-48ee-af64-9cead2089cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DraganddropObj/testXlsxedit/iframe_Capture object_frame</value>
      <webElementGuid>67bc23af-b042-4438-9cb4-679ea035157e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Viewing'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>6deb4132-d7c9-4f6d-9d53-2456e870980b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Viewing'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>89a9772e-2c36-44aa-aa0d-d4739305ac7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comments'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>dcc9170a-c38a-4f6f-b1be-814f319944a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='There is nothing to undo.'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>01ffa05c-2365-4639-ac95-51053a6ce625</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
