<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>View_Doc_Request_CA_Client_Login</name>
   <tag></tag>
   <elementGuidId>ac724d6e-5bd6-4a86-958a-f810697b49d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body/div/div/mat-accordion[@multi='true']/mat-expansion-panel/div[@role='region']/div/mat-list[@role='list']/mat-list-item[@role='listitem']/span/span/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
