<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Onboarding_Sign_Up_Suite_Prod</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d8ba1d99-3daa-48f3-98b7-888de412f218</testSuiteGuid>
   <testCaseLink>
      <guid>3b310062-aa44-43ef-ac14-bcc967730e95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script1_SignUp-Countable_Canada</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fa39a83-6eb6-4fb6-a7be-db658d7cca26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e1da4e7-e9c6-4800-a57b-f3e0d9c05398</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d6a503a-64da-4713-b0dc-aef639f21a1b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script2_Onboarding_Client_Team_Firm_Canada_New</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b08e9c0-ad7a-49b9-b04f-9c44845320f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e78f670-41af-4e46-950e-9d9dd48b7ff6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcda68d7-0965-4a55-acea-fe941be2df9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64e116f6-5fba-4c0b-b061-79c8aa796622</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b82dab2-4951-4fb9-9e47-4529e510839c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
