<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Prod_Suite_1st</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e05d37d0-9161-4d8b-b1e2-1c825dbff4ae</testSuiteGuid>
   <testCaseLink>
      <guid>24df0326-8567-4597-ae46-fe372504053a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script1_SignUp-Countable_Canada</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fa39a83-6eb6-4fb6-a7be-db658d7cca26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e1da4e7-e9c6-4800-a57b-f3e0d9c05398</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20495602-b3be-451b-a681-2e8f6f7fc8f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script2_Onboarding_Client_Team_Firm_Canada_New</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b08e9c0-ad7a-49b9-b04f-9c44845320f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e78f670-41af-4e46-950e-9d9dd48b7ff6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcda68d7-0965-4a55-acea-fe941be2df9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64e116f6-5fba-4c0b-b061-79c8aa796622</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b82dab2-4951-4fb9-9e47-4529e510839c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7950389-ed6a-4f23-bc7a-610b80c2f624</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script3_Add_Signature_To_Frm_User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a6a34f6-b79d-4597-bc2b-d75bc1898a93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3d56930-5bc5-4229-ad11-a763775ed53b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script4_Add_Firm_Template_All</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47916767-7482-4c60-a23e-18140ba46b7b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>30f4a731-858b-4d02-9050-cfc43331d8f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script5_Inside_Engagement_LHS_All</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2916b938-1823-4029-a069-c7dcc64dab61</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
