<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Prod_Suite_3rd</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8320934c-5d23-4b00-ba19-4990da244ec8</testSuiteGuid>
   <testCaseLink>
      <guid>f9e59436-8258-482e-aa4d-5019a405e48e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_10_Add_Update_Client_All_Case</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>356e03c0-045b-4ed9-8507-6ff02d645e23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2959ecdb-2018-4d45-ae1e-900b37474d63</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7848a320-cdb3-416b-839d-8044b3002dbb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_11_Add_Update_Team_All_Reg_Case</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4899dc74-d5a9-4cf9-9ffa-c3e77b68bfc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8a0f62e-640e-4ddd-ad76-8f2060bf3de7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f876a52d-a6a8-4514-b35e-fcb9a969a937</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e664cc23-131e-42a2-a93a-5617f47037e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b803cc3a-fac6-4209-a963-2c089038a0ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_12_Sign-Offs-1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c76ce4ae-3928-4b00-8c5b-f66577d568c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>170a5a08-d933-4caf-ba6e-7f03282de47a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>166bf9cf-8f68-4d93-afb0-7ae1ba9aa7b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a35a31e-c3f8-4b6c-a60d-12fff24ace85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6d0e7a5-98d7-4eec-9111-deca53653567</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a76cb1da-e30e-4400-8419-6f75245f00ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71a84ddc-e8bc-488e-9cf5-fa56a82738f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c85b90f-8dd4-4a5d-8b9f-803107b29ceb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1fbee98-b2d9-4a60-b2c8-dda122f42158</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e64e2b6f-b639-4699-b976-fe949a3f452e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b7315e5-30a1-4c00-ab1e-0b044779b9e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>974fc345-e3f6-43a8-960d-4f546ed1f767</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5a13d54-91a4-4614-8fcc-ab9159cb5d70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61b7f2eb-4642-4979-99c1-5817ae20c755</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>641e847e-d12d-4ef6-976f-4ade95dc6d80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1fed8a1-9625-471b-87f5-5834942e6e92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4c957ce-afdc-4490-a13b-6cfdeac245af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93e9ceca-e56b-4c42-aa45-2d341d6b0765</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_13_Final Review_All_Cases</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94be40cc-aadc-4cec-8c8b-d4d4aa1b036a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2962d0d5-dca2-4694-824b-d6b7002672c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_14_Import_Trial_Balance_Compilation_Engagement</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e80d6e10-0d22-483c-89dc-884091f66c6d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
