<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WelcomeEmailDiv</name>
   <tag></tag>
   <elementGuidId>60c061da-c4cf-4168-8265-b3d935666bed</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[id='e_ZwDjAQV5ZGDlZmHlZQNjAGR1ZGt5BN=='] button[class='lm']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_ZwDjAQV5ZGDlZmHlZQNjAGR1ZGt5BN==']//button[@class='lm']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
