<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Onboarding and SignUp Suite_Canada</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d2dc6f62-5788-4803-b84b-dea87ac52c5a</testSuiteGuid>
   <testCaseLink>
      <guid>44a32694-ce33-43c0-bd16-5b34e05d3732</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_UAT_Environment_Scripts/Script1_SignUp-Countable_Canada</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38b3800d-481c-4462-ae64-518a5b4928b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d5504b2-b67f-45aa-8398-a1bc7ad865f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c46be7b-1cfc-4811-b5ae-8867576a8cad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_UAT_Environment_Scripts/Script2_Onboarding_Client_Team_Firm_Canada_New</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0c13d47-6905-497f-ad6c-3768d1d926b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bd6479a-5227-4422-8971-26c8c1527267</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a560696e-f59c-4d33-b6c5-e6339acb61e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0a5fd1f-df9c-4e49-9782-fa257a1e0e19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b29dc95-524b-4f8e-a59a-747355a3c3b8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
