<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regression_Suite_Canada</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>eee79c6e-dc09-42b5-982e-6b99a672b5f7</testSuiteGuid>
   <testCaseLink>
      <guid>f5699704-6889-4400-bc49-33159475571d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script1_SignUp-Countable_Canada</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fa39a83-6eb6-4fb6-a7be-db658d7cca26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e1da4e7-e9c6-4800-a57b-f3e0d9c05398</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e36f81a4-9041-436b-a93b-8881de692078</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script2_Onboarding_Client_Team_Firm_Canada_New</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b08e9c0-ad7a-49b9-b04f-9c44845320f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e78f670-41af-4e46-950e-9d9dd48b7ff6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcda68d7-0965-4a55-acea-fe941be2df9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64e116f6-5fba-4c0b-b061-79c8aa796622</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b82dab2-4951-4fb9-9e47-4529e510839c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89e123db-bad8-451d-9545-a143b13fb328</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script3_Add_Signature_To_Frm_User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a6a34f6-b79d-4597-bc2b-d75bc1898a93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>380dc17a-f975-4e49-a541-381f1063f0f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script4_Add_Firm_Template_All</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47916767-7482-4c60-a23e-18140ba46b7b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f226dc92-610e-46a6-8f51-d38fc7e3cb40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script5_Inside_Engagement_LHS_All</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2916b938-1823-4029-a069-c7dcc64dab61</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2570fc25-d47e-461c-9486-a2a87d1001ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script6_Inside_Eng_RHS_All</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>320681bd-1d69-40e8-8ae7-37415796ca1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f659ebc9-1746-4479-a13a-9cb978a61dd3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb455774-d368-484e-bc00-5b353b1a8da1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script7_CreateEnagagement_1_Eng_Sec_Client_Sec</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1138d1e1-ff37-4f33-88b2-c355de1149c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39701b35-fe87-4675-ad72-7404e7e7ab3d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script8_Create_Update_Engagement_2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27e737ee-d75b-43a8-a15f-bfd54a927069</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d65904c-c08c-4453-b6b9-240e43154547</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5230daca-f04d-475e-bb1a-648656e370f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87f84828-3877-4bd4-9a17-be3e51fe95ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script9_Create_Update_Eng_3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2af2d3a0-d622-445a-9bbc-c49b8701a180</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e34fd390-8c7d-4842-8d08-026f777e7e79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_10_Add_Update_Client_All_Case</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>356e03c0-045b-4ed9-8507-6ff02d645e23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2959ecdb-2018-4d45-ae1e-900b37474d63</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c8f4dc0-c955-44b7-b4bb-7c86f5a54f65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_11_Add_Update_Team_All_Reg_Case</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4899dc74-d5a9-4cf9-9ffa-c3e77b68bfc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8a0f62e-640e-4ddd-ad76-8f2060bf3de7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f876a52d-a6a8-4514-b35e-fcb9a969a937</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e664cc23-131e-42a2-a93a-5617f47037e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea5c4c73-fb55-4d3e-82f0-d295abcf0920</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_12_Sign-Offs-1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c76ce4ae-3928-4b00-8c5b-f66577d568c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>170a5a08-d933-4caf-ba6e-7f03282de47a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>166bf9cf-8f68-4d93-afb0-7ae1ba9aa7b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a35a31e-c3f8-4b6c-a60d-12fff24ace85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6d0e7a5-98d7-4eec-9111-deca53653567</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a76cb1da-e30e-4400-8419-6f75245f00ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71a84ddc-e8bc-488e-9cf5-fa56a82738f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c85b90f-8dd4-4a5d-8b9f-803107b29ceb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1fbee98-b2d9-4a60-b2c8-dda122f42158</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e64e2b6f-b639-4699-b976-fe949a3f452e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b7315e5-30a1-4c00-ab1e-0b044779b9e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>974fc345-e3f6-43a8-960d-4f546ed1f767</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5a13d54-91a4-4614-8fcc-ab9159cb5d70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61b7f2eb-4642-4979-99c1-5817ae20c755</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>641e847e-d12d-4ef6-976f-4ade95dc6d80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1fed8a1-9625-471b-87f5-5834942e6e92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4c957ce-afdc-4490-a13b-6cfdeac245af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73d87a31-d5c0-435f-9ab6-aae7fe406033</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_13_Final Review_All_Cases</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94be40cc-aadc-4cec-8c8b-d4d4aa1b036a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7320e6d7-dda4-4da8-a3b3-e7ed7291282c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_14_Import_Trial_Balance_Compilation_Engagement</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e80d6e10-0d22-483c-89dc-884091f66c6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6be8d3c-8ee8-4533-829a-b73cd9544e0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_15_Create_FS_Pakage_Send_Pkg</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a929769c-3d15-4b78-aa47-64d1fabae55b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e71e0969-5576-4cf5-853c-2a95da833426</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>218b95d8-2df1-42bb-b9ae-f0fdcc7f077c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67781e29-5733-4050-aa50-c1a391aff08b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_16_Create_Engagement_From_Client_Section</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29c7dd80-f00a-4099-89b5-d053e07d86e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>057271f4-1d73-4b33-a344-a31bff1ccb65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_17_Engagement_Archived_Validation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>311349f1-794f-42cc-829a-56311a89df48</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eeea632d-5af7-4a8e-8e4a-05e5c674d799</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_18_Complete_Engagement_Validation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a401b8a9-d425-4263-a9c3-66a207a35a5a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b54a36b2-3639-4c68-89f8-70c621c6067f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_19_Complete_Engagement_Comp_Rev_Tax</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbc48371-5b3e-4545-9c59-89c9a54ecf70</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04b6f844-df79-46ca-8006-bc93c6f7c1f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_20_Engagement_Archived - AllType</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53e1398b-146b-4adb-8e3c-d5a9a33ead61</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c4f0e431-1fef-4c28-975c-a16992b5a6dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_21_Enagement_Dashboard_Status_Filter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62b3f2bc-d8fc-47e1-9c35-40e44e32e9ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27c17781-bb61-40bc-8581-833c697f2b8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_Production_Environment/Script_22_Engagement_Letter_Text_Verification</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0af960a5-c49e-4698-82e1-9b26cac87569</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f5b3d00-b71e-4e99-9008-ce7d92952139</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dff00f57-cabb-4e00-a204-166c88ba3418</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
