<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Sign-Up Onboarding-USA</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f9643fe2-0a7b-44eb-a4f1-ee62be423728</testSuiteGuid>
   <testCaseLink>
      <guid>ec85915f-74a3-4dd7-9685-48ddefc758fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_UAT_Environment_Scripts/Script_23_SignUp-Countable_USA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>440efe2a-32d6-47a9-af4d-49e619e694bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e64a48a2-fed1-4841-bfcb-21a36e176d93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe7006db-0805-453e-b370-0a2c0273d18d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_UAT_Environment_Scripts/Script_24_OnboardFirmTeamClient_USA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b070315-a345-42e2-992c-014c4fe44b76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8d52dcb-5fea-4af6-b5fa-dd59f73b6965</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>729caf75-82c7-4d36-af4e-b6ceeb443e82</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
