<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Container_COUNTABLE FLEXPLAN TERMS</name>
   <tag></tag>
   <elementGuidId>43eaeb56-fcf1-487c-a898-27493e1c2000</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div/div[@dir='ltr']/div/mat-dialog-container[@role='dialog']/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-mdc-dialog-title-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0740ad67-891b-43e8-b71b-022d26c47149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-dialog-title mdc-dialog__title dialog-header d-flex flex-column</value>
      <webElementGuid>82bd7486-1e1e-4b0b-91de-2f3030cf009b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-mdc-dialog-title-0</value>
      <webElementGuid>8585e779-8faa-410e-a368-2c1afe9260cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>closeCOUNTABLE FLEXPLAN TERMS </value>
      <webElementGuid>335e5606-4751-44b9-bf24-65da6cccd661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-dialog-title-0&quot;)</value>
      <webElementGuid>163fccc8-7deb-4606-8600-583f1a504871</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//body/div/div[@dir='ltr']/div/mat-dialog-container[@role='dialog']/div/div/div/div[2]</value>
      <webElementGuid>033795f9-7c1b-409d-a3fb-75e2ac31d6ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body/div/div[@dir='ltr']/div/mat-dialog-container[@role='dialog']/div/div/div/div[2]</value>
      <webElementGuid>92dbe1e9-a222-445f-b681-7adb0411185f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clear'])[2]/following::div[10]</value>
      <webElementGuid>e1b8271b-2106-469b-ad62-fd01de7969cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clear'])[1]/following::div[16]</value>
      <webElementGuid>103ef30b-2a59-4c97-b2f5-9603074fe66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container/div/div/div/div</value>
      <webElementGuid>24191f67-be95-4df1-88ea-bb54049c7046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-mdc-dialog-title-0' and (text() = 'closeCOUNTABLE FLEXPLAN TERMS ' or . = 'closeCOUNTABLE FLEXPLAN TERMS ')]</value>
      <webElementGuid>c7441752-3d48-4300-9fb2-1680d96535c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
