<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Enter payment details___privateStripeFrame8274</name>
   <tag></tag>
   <elementGuidId>7d16c941-fdb6-4eab-84e8-788b7f69979f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@title='Secure payment input frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame8274&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'https://js.stripe.com/v3/elements-inner-payment-fe281403f4d19870ac14528effde313a.html#wait=false&amp;rtl=false&amp;publicOptions[defaultValues][billingDetails][address][country]=CA&amp;publicOptions[defaultValues][billingDetails][address][postal_code]=L3M+1P3&amp;publicOptions[layout][type]=accordion&amp;publicOptions[layout][defaultCollapsed]=false&amp;publicOptions[layout][radios]=true&amp;publicOptions[layout][spacedAccordionItems]=true&amp;componentName=payment&amp;keyMode=test&amp;apiKey=pk_test_0OVDEXxxM4L1l1OAq8eTRnge004iidmxOw&amp;referrer=https%3A%2F%2Fuat.adinovis.com%2Fdashboard%2Fmembers%2Fsettings%2Fbilling%2Fcheckout&amp;controllerId=__privateStripeController8271' and @title = 'Secure payment input frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d0d6a20c-53ee-472c-96e0-badf79ebd2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame8274</value>
      <webElementGuid>919b4ded-06f5-4ea3-9ac5-57785ed43dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ca411dca-9721-442b-8366-ca2eecd786fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a472136d-9571-4a77-8099-b4bd18af165a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d28cf02f-2631-4cb0-be3c-a15821e364d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>1337de72-d281-4057-9d41-57ccef45a4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>payment *; publickey-credentials-get *</value>
      <webElementGuid>38391126-d13c-4c14-83f2-54f26f2cd78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-payment-fe281403f4d19870ac14528effde313a.html#wait=false&amp;rtl=false&amp;publicOptions[defaultValues][billingDetails][address][country]=CA&amp;publicOptions[defaultValues][billingDetails][address][postal_code]=L3M+1P3&amp;publicOptions[layout][type]=accordion&amp;publicOptions[layout][defaultCollapsed]=false&amp;publicOptions[layout][radios]=true&amp;publicOptions[layout][spacedAccordionItems]=true&amp;componentName=payment&amp;keyMode=test&amp;apiKey=pk_test_0OVDEXxxM4L1l1OAq8eTRnge004iidmxOw&amp;referrer=https%3A%2F%2Fuat.adinovis.com%2Fdashboard%2Fmembers%2Fsettings%2Fbilling%2Fcheckout&amp;controllerId=__privateStripeController8271</value>
      <webElementGuid>f38aa20e-da90-4be0-8c7c-f3d8e5a4e882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure payment input frame</value>
      <webElementGuid>1af0b319-3f0b-4cf7-bb37-dcdcad546bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-element&quot;)/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
      <webElementGuid>e8eaa635-21cc-4417-b90a-4b370942d02d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame8274']</value>
      <webElementGuid>43fa5e0d-8dd7-4b8d-944b-5f66a62e62af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-element']/div/iframe</value>
      <webElementGuid>7dea0713-1627-4eac-8057-b51dd6e5ed5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>fd3d94e0-b197-48da-b772-d82f6d01fd74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame8274' and @src = 'https://js.stripe.com/v3/elements-inner-payment-fe281403f4d19870ac14528effde313a.html#wait=false&amp;rtl=false&amp;publicOptions[defaultValues][billingDetails][address][country]=CA&amp;publicOptions[defaultValues][billingDetails][address][postal_code]=L3M+1P3&amp;publicOptions[layout][type]=accordion&amp;publicOptions[layout][defaultCollapsed]=false&amp;publicOptions[layout][radios]=true&amp;publicOptions[layout][spacedAccordionItems]=true&amp;componentName=payment&amp;keyMode=test&amp;apiKey=pk_test_0OVDEXxxM4L1l1OAq8eTRnge004iidmxOw&amp;referrer=https%3A%2F%2Fuat.adinovis.com%2Fdashboard%2Fmembers%2Fsettings%2Fbilling%2Fcheckout&amp;controllerId=__privateStripeController8271' and @title = 'Secure payment input frame']</value>
      <webElementGuid>ff48a53d-7143-476f-9e1a-a59d4852cc7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
