<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card number_number</name>
   <tag></tag>
   <elementGuidId>96cd918f-9253-4df1-b6db-ab3300395dd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Field-numberInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Field-numberInput</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Field-numberInput&quot;)[count(. | //*[@type = 'text' and @name = 'number' and @id = 'Field-numberInput' and @placeholder = '1234 1234 1234 1234' and @ref_element = 'Object Repository/StripePayment/iframe_Enter payment details___privateStripeFrame8274']) = count(//*[@type = 'text' and @name = 'number' and @id = 'Field-numberInput' and @placeholder = '1234 1234 1234 1234' and @ref_element = 'Object Repository/StripePayment/iframe_Enter payment details___privateStripeFrame8274'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21edec58-e04a-4af8-be0c-0481218451ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>a2d7dfbd-7f75-48de-a870-cb53bdd908c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c6722877-d1e5-4408-963b-f42097b8d064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>7fed583e-6b71-4809-89fc-11153efc701b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8b362420-0f32-460e-814d-2f70a8426999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Field-numberInput</value>
      <webElementGuid>e7445d56-a66b-4e86-8404-6ef1a3e4f12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1234 1234 1234 1234</value>
      <webElementGuid>f2f78782-48b3-48fe-a9c0-e6a156826388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>billing cc-number</value>
      <webElementGuid>500fb3e0-2c04-4ea6-9a78-28acda951e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f00bbd64-d5f1-4a66-815f-57d684e8ed5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>null knownCardBrandDesc cardBrandIconsDesc</value>
      <webElementGuid>8e7b8741-c517-47b3-8538-5230710f3d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d3348d93-2d85-41c3-95e2-65ad5e85773e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-Input-input Input p-CardNumberInput-input p-Input--focused Input--empty p-Input-input--textRight</value>
      <webElementGuid>6b388275-9300-49d4-9908-62cabe116ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Field-numberInput&quot;)</value>
      <webElementGuid>9df3088e-ba83-4b09-b7aa-e078ad212b83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Field-numberInput']</value>
      <webElementGuid>1acaaf29-a333-461d-9833-8f5de45112b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card']/div/div/form/div/div/div/div/div/div/div/input</value>
      <webElementGuid>d0da48a8-4fc1-435c-8322-e379a13eeaa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d5e521be-69da-49e8-93ec-a1f695022706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'number' and @id = 'Field-numberInput' and @placeholder = '1234 1234 1234 1234']</value>
      <webElementGuid>1ff019b8-7c17-4273-bdac-05738e6c1cd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
