<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Proceed_To_Downgrade</name>
   <tag></tag>
   <elementGuidId>d94307bc-141f-49ce-90a3-76e20b9c05f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[normalize-space()='Proceed']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button-medium.flex-1.w-100.mdc-button.mat-mdc-button.mdc-button--unelevated.mat-mdc-unelevated-button.mat-primary.mat-mdc-button-base > span.mdc-button__label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d1eaa18e-18ea-4185-bd59-d60fc65794f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-button__label</value>
      <webElementGuid>d658785f-8e60-44b5-a7ce-0fae42233d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Confirm and Pay </value>
      <webElementGuid>7c85d613-611b-4f00-bbf8-3bceebe6bdaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parentDiv&quot;)/stripe-check-out[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;cards-group gap-20 flex-xl-nowrap px-20&quot;]/div[@class=&quot;card flex-1 ng-star-inserted&quot;]/div[@class=&quot;card-body gap-20 ng-star-inserted&quot;]/div[@class=&quot;d-flex flex-column gap-4&quot;]/div[@class=&quot;heading d-flex flex-row align-items-center justify-content-center button-group middle-content py-20 ng-star-inserted&quot;]/button[@class=&quot;button-medium flex-1 w-100 mdc-button mat-mdc-button mdc-button--unelevated mat-mdc-unelevated-button mat-primary mat-mdc-button-base&quot;]/span[@class=&quot;mdc-button__label&quot;]</value>
      <webElementGuid>58b3fa8f-d372-4306-92c2-8036f68a9f7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[normalize-space()='Proceed']</value>
      <webElementGuid>3bfe0ab6-500b-4bee-838e-886a0899c619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default'])[1]/following::span[2]</value>
      <webElementGuid>76ee8f0c-5058-46eb-a151-24142b7601d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiry 02/20XX'])[1]/following::span[3]</value>
      <webElementGuid>6432e040-9f6d-475d-9017-6b781032d368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm and Pay']/parent::*</value>
      <webElementGuid>5552ec47-de57-4516-bbae-b9fd178a933c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span[2]</value>
      <webElementGuid>f3ab6af3-6fa3-401f-9ac5-eaf32a85c959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Confirm and Pay ' or . = ' Confirm and Pay ')]</value>
      <webElementGuid>1096f8d3-e6da-4c34-80a7-e4c67f7a37b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
