<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Deactiavte_Confirm_Proceed</name>
   <tag></tag>
   <elementGuidId>abed3c2c-71f8-4d39-9976-20d5cc2b1ba1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']//span[@class='mdc-button__label'][normalize-space()='Deactivate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button-medium.flex-1.w-100.mdc-button.mat-mdc-button.mdc-button--unelevated.mat-mdc-unelevated-button.mat-primary.mat-mdc-button-base > span.mdc-button__label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c1158d93-d230-4967-b751-87781d3c8d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-button__label</value>
      <webElementGuid>b6b2dccf-70e4-4edf-8f7e-00b7931d6029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Confirm and Pay </value>
      <webElementGuid>0fb9e485-e422-4b7a-8cd5-a54cff0ce3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parentDiv&quot;)/stripe-check-out[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;cards-group gap-20 flex-xl-nowrap px-20&quot;]/div[@class=&quot;card flex-1 ng-star-inserted&quot;]/div[@class=&quot;card-body gap-20 ng-star-inserted&quot;]/div[@class=&quot;d-flex flex-column gap-4&quot;]/div[@class=&quot;heading d-flex flex-row align-items-center justify-content-center button-group middle-content py-20 ng-star-inserted&quot;]/button[@class=&quot;button-medium flex-1 w-100 mdc-button mat-mdc-button mdc-button--unelevated mat-mdc-unelevated-button mat-primary mat-mdc-button-base&quot;]/span[@class=&quot;mdc-button__label&quot;]</value>
      <webElementGuid>5410302f-4ffd-4c65-a855-b4d4718fbb57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@type='button']//span[@class='mdc-button__label'][normalize-space()='Deactivate']</value>
      <webElementGuid>0ffd7404-52f7-43dd-8c4f-00b469bce89f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default'])[1]/following::span[2]</value>
      <webElementGuid>845e5c0f-8f89-4af5-b2c5-184fa23bb61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiry 02/20XX'])[1]/following::span[3]</value>
      <webElementGuid>263e996f-5d6b-44a3-b141-10cb3025c49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm and Pay']/parent::*</value>
      <webElementGuid>09b3254c-0f55-49d7-ad59-31f711e3585d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span[2]</value>
      <webElementGuid>acae57e3-2e1c-403e-b896-beee1af50578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Confirm and Pay ' or . = ' Confirm and Pay ')]</value>
      <webElementGuid>7d829bc0-b2d6-48ff-a823-056502f963d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
