<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Say Goodbye toManual Work_wp-image-1718_641827</name>
   <tag></tag>
   <elementGuidId>744a1eb1-a9a2-4b8b-9947-5b3779f067c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.wp-image-17187.alignnone.size-medium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-16000']/div/div/div/div/div/div/div[4]/div/p/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1bdc6c3a-b615-4ba6-a090-349cfa374b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>1b060f8e-0f5a-455e-a440-fe3acab89ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-image-17187 alignnone size-medium</value>
      <webElementGuid>ec2395c3-7ad3-43f0-ab6a-5997b785604d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://countable.co/wp-content/uploads/2023/10/image-27-1-300x66.png</value>
      <webElementGuid>a5746b16-ecff-4d71-b204-3b285cf11700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>39eea7f8-090c-46a0-92c9-e77b22dfd430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>d8ffd0bf-7e00-440b-97ad-d7067c740513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-16000&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;et-l et-l--post&quot;]/div[@class=&quot;et_builder_inner_content et_pb_gutters3&quot;]/div[@class=&quot;et_pb_section et_pb_section_0 hmb et_pb_with_background et_section_regular&quot;]/div[@class=&quot;et_pb_row et_pb_row_0 hmr&quot;]/div[@class=&quot;et_pb_column et_pb_column_1_2 et_pb_column_0 hmtop  et_pb_css_mix_blend_mode_passthrough&quot;]/div[@class=&quot;et_pb_module et_pb_text et_pb_text_3  et_pb_text_align_left et_pb_bg_layout_light&quot;]/div[@class=&quot;et_pb_text_inner&quot;]/p[1]/a[@class=&quot;etr&quot;]/img[@class=&quot;wp-image-17187 alignnone size-medium&quot;]</value>
      <webElementGuid>2b390938-0c99-46b9-b745-d8db6dee3eb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-16000']/div/div/div/div/div/div/div[4]/div/p/a/img</value>
      <webElementGuid>fd5c6c1e-6d17-4967-b413-eaa1e0400a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://countable.co/wp-content/uploads/2023/10/image-27-1-300x66.png')]</value>
      <webElementGuid>4d845c36-912f-41d0-9c50-86a99ba8d3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a/img</value>
      <webElementGuid>0d411b5f-bd21-489b-a102-d39af2760883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://countable.co/wp-content/uploads/2023/10/image-27-1-300x66.png']</value>
      <webElementGuid>f79cf452-7b3f-4ee9-b71f-522aa300628b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
