<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Verify</name>
   <tag></tag>
   <elementGuidId>59a88558-62e9-4a15-865d-eaae26f16f55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Verify')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b221414e-4a22-444c-9e16-17fcae9cd2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat.adinovis.com/setpassword?token=N2M2OTNiOTItMGQ4NS00N2IxLTljNmUtNWJmNWJhMWRjMTQ2</value>
      <webElementGuid>b896fdd4-4eb9-4412-a585-83a6a4350fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify
                                    Email</value>
      <webElementGuid>3d0f6fce-d4f4-473c-ac5f-c6f2b9e79beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail&quot;)/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/table[1]/tbody[1]/tr[4]/td[1]/a[1]</value>
      <webElementGuid>2e25389f-ae17-4231-9931-babcdb9032a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Inbox/iframe_Undo_ifmail</value>
      <webElementGuid>27baf8e3-7c31-4dbc-81ed-48a5f5b7977a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[contains(text(),'Verify')]</value>
      <webElementGuid>b8580a9c-6cc4-49bb-b339-b6615d738e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Verify
                                    Email')]</value>
      <webElementGuid>d5104a64-bf18-4683-b734-ee546fe9bf7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat.adinovis.com/setpassword?token=N2M2OTNiOTItMGQ4NS00N2IxLTljNmUtNWJmNWJhMWRjMTQ2')]</value>
      <webElementGuid>1733c86e-8403-4784-81a5-a86c262b5208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>627e7e95-5ca5-43c5-912d-f0b3666215ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat.adinovis.com/setpassword?token=N2M2OTNiOTItMGQ4NS00N2IxLTljNmUtNWJmNWJhMWRjMTQ2' and (text() = 'Verify
                                    Email' or . = 'Verify
                                    Email')]</value>
      <webElementGuid>dcc7a519-5a7e-4bf7-969c-d3a623100ac1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
