<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Verify                                    Email (1)</name>
   <tag></tag>
   <elementGuidId>1657ae87-4682-4725-91ea-ca7ca1d8259c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mail']/div/div/table/tbody/tr[2]/td/div/table/tbody/tr[4]/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>936f4b72-15e0-4f33-bdbd-25729434bef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat.adinovis.com/setpassword?token=YjY2ZGRhNjYtY2Q0NC00MzMyLTliMGEtZGNjODYzY2FjYWYz</value>
      <webElementGuid>9d674a56-6028-4ee5-a908-be439c646d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify
                                    Email</value>
      <webElementGuid>836c1264-0e61-4eff-ad38-bf28e01bbb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail&quot;)/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/table[1]/tbody[1]/tr[4]/td[1]/a[1]</value>
      <webElementGuid>05b482eb-a310-4277-a4fd-23db6944e04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Inbox/iframe_Undo_ifmail (1)</value>
      <webElementGuid>8f4586c0-0f34-4138-b5cd-c048075535a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mail']/div/div/table/tbody/tr[2]/td/div/table/tbody/tr[4]/td/a</value>
      <webElementGuid>a6ae318c-3e4c-45d1-aec2-b876e0780722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Verify
                                    Email')]</value>
      <webElementGuid>d64f3f2f-7662-4488-bd0b-3aea6328d86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat.adinovis.com/setpassword?token=YjY2ZGRhNjYtY2Q0NC00MzMyLTliMGEtZGNjODYzY2FjYWYz')]</value>
      <webElementGuid>880787ae-5a13-493f-8cd2-3d6a8164fda1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>d5f1b124-5262-47b8-9b9f-f3443ef3cdaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat.adinovis.com/setpassword?token=YjY2ZGRhNjYtY2Q0NC00MzMyLTliMGEtZGNjODYzY2FjYWYz' and (text() = 'Verify
                                    Email' or . = 'Verify
                                    Email')]</value>
      <webElementGuid>84f7dc53-41e1-4d75-8af8-d316b96d5839</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
