<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Verify                                    Email (2)</name>
   <tag></tag>
   <elementGuidId>caeca40d-7cf3-4f54-bcdd-372ffa6e1f77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mail']/div/div/table/tbody/tr[2]/td/div/table/tbody/tr[4]/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>79f73f89-ff54-4ffe-8c22-d77de8d1700c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat.adinovis.com/setpassword?token=Nzk2ZWY4MmYtOTQ1OS00N2Y2LThlNDQtODFjNGMzNWU1YmVl</value>
      <webElementGuid>ef296443-3e64-4d7d-8ebd-7ab3d733a498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify
                                    Email</value>
      <webElementGuid>a9ddaece-0a42-4abf-bcf5-bbe09d30188a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail&quot;)/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/table[1]/tbody[1]/tr[4]/td[1]/a[1]</value>
      <webElementGuid>6e0e2e11-ce45-4b58-baad-51417192a498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Inbox/iframe_Undo_ifmail (2)</value>
      <webElementGuid>cdeb1bb0-bf11-42f2-a7bd-97c36d90d943</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mail']/div/div/table/tbody/tr[2]/td/div/table/tbody/tr[4]/td/a</value>
      <webElementGuid>6ac79be2-39af-41cc-9954-2db033a69661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Verify
                                    Email')]</value>
      <webElementGuid>d4742a3d-92dd-4584-9b69-ddcc0c6f3066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat.adinovis.com/setpassword?token=Nzk2ZWY4MmYtOTQ1OS00N2Y2LThlNDQtODFjNGMzNWU1YmVl')]</value>
      <webElementGuid>731c407c-38cb-46c8-9a7f-3104556fe079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>f22196fd-d084-4c68-bebc-1694e6af1cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat.adinovis.com/setpassword?token=Nzk2ZWY4MmYtOTQ1OS00N2Y2LThlNDQtODFjNGMzNWU1YmVl' and (text() = 'Verify
                                    Email' or . = 'Verify
                                    Email')]</value>
      <webElementGuid>f3d369ba-9065-4992-a47b-1fc4bfe54ac5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
