<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Undo_ifinbox</name>
   <tag></tag>
   <elementGuidId>f7a65421-c126-46c2-9c41-648ef62253ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ifinbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifinbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>053919a2-94e7-4de7-a614-d5593ef5d48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifinbox</value>
      <webElementGuid>2798a224-2116-4781-a099-16577b3be2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>onloadifinbox()</value>
      <webElementGuid>b7616ef7-7f11-4cd0-9eaa-5f41e3b3c381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifinbox</value>
      <webElementGuid>f7e11c14-3800-4ad1-94dd-c2abfd973b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>state</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>e0915ac8-a791-4c80-82d3-3190a16321a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifinbox&quot;)</value>
      <webElementGuid>c31b74c4-f748-479e-afe2-a2353eb727f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifinbox']</value>
      <webElementGuid>c741a08c-edb1-40d5-a371-fd47aaa63502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wminboxmain']/iframe</value>
      <webElementGuid>de243dab-d24d-4d5c-8538-b8918e56c21f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>755a1a8c-2fe3-48d5-ab9f-47f8b1a9f9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'ifinbox' and @id = 'ifinbox']</value>
      <webElementGuid>14e12c7a-5af1-4556-988b-ca5d9ccf4dbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
