<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_adminadinovis.com</name>
   <tag></tag>
   <elementGuidId>198ff2c9-4903-4e1c-95dc-58bb29b86285</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_ZwDjAQN4ZGRjZmNjZQNjZmLjZmD4AN==']/button/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.lmf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2068a4a2-b636-4429-8127-9ef958d074f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lmf</value>
      <webElementGuid>15a454bf-2354-4489-8a86-b8f32fe7e0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>admin@adinovis.com</value>
      <webElementGuid>5085f49a-807e-4989-a8c3-4b86dccc5b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_ZwDjAQN4ZGRjZmNjZQNjZmLjZmD4AN==&quot;)/button[@class=&quot;lm&quot;]/div[@class=&quot;lmfd&quot;]/span[@class=&quot;lmf&quot;]</value>
      <webElementGuid>3d664558-d08b-4036-b881-64020fdaadf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Inbox/iframe_Undo_ifinbox (1)</value>
      <webElementGuid>c19a91e9-1fcd-4fef-ab84-c2611da556dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e_ZwDjAQN4ZGRjZmNjZQNjZmLjZmD4AN==']/button/div/span[2]</value>
      <webElementGuid>40d0a29f-cb5b-4858-a1da-7b163e2ab58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[1]/following::span[2]</value>
      <webElementGuid>a9c5f4a0-2199-4d11-b458-59205b6d2f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to Countable'])[1]/preceding::span[1]</value>
      <webElementGuid>6e63c369-fe70-442b-96c5-8ac1ee0e94eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin@adinovis.com'])[2]/preceding::span[2]</value>
      <webElementGuid>005f6910-3772-4103-b27d-058483d1cfe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='admin@adinovis.com']/parent::*</value>
      <webElementGuid>ec2a9288-9fd1-4d7b-abb0-0815580e2ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>08a128db-b6f7-4452-a521-af16f993c4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'admin@adinovis.com' or . = 'admin@adinovis.com')]</value>
      <webElementGuid>a836a48f-5d14-4456-8be4-88c92a07fa27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
