<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Click to upload or Drag and drop the file (CSVExcel)</name>
   <tag></tag>
   <elementGuidId>67382e60-c3b0-4615-ad82-a5ec41bfb2aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='importTrailBalance']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#importTrailBalance</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>388f3da3-e708-410f-a5e9-79859b42b806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>importTrailBalance</value>
      <webElementGuid>205cd54b-b56f-4dd9-afb3-83dd15ead03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cdk-drop-list file-upload</value>
      <webElementGuid>74d90d7e-18c1-4a1a-83dd-5efb093f8169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click to upload or Drag and drop the file (CSV/Excel)</value>
      <webElementGuid>5b96b5a2-d4fb-4eae-9b18-f386c82106cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;importTrailBalance&quot;)</value>
      <webElementGuid>1c000147-5746-4b50-9ec3-ea4b91d2dff7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='importTrailBalance']</value>
      <webElementGuid>b34a138c-b44e-488b-8652-593c317da004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dec 31, 2023'])[1]/following::div[7]</value>
      <webElementGuid>981bc36e-5148-4a04-9767-df52695447b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year End Date'])[1]/following::div[9]</value>
      <webElementGuid>6b053d05-7b59-4263-989c-96a154196149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Template'])[1]/preceding::div[3]</value>
      <webElementGuid>48b8c173-9e9d-475b-87d6-605c657c712a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div</value>
      <webElementGuid>9d03ec2a-288b-4b52-ba20-0995d2f231db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'importTrailBalance' and (text() = 'Click to upload or Drag and drop the file (CSV/Excel)' or . = 'Click to upload or Drag and drop the file (CSV/Excel)')]</value>
      <webElementGuid>53970c35-7b74-43a5-b0eb-e5cecd45da3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
