<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Confirmation_DeleteTeam_Mem_BTN_AllClient</name>
   <tag></tag>
   <elementGuidId>0a7e60c3-423c-43a6-a009-f7fe5af92f05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[normalize-space()='Delete']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[normalize-space()='Delete']</value>
      <webElementGuid>a9dd426f-0c56-4402-8be0-838e8f7d138b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
