<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Confirmation_SaveButton_Edit_Details</name>
   <tag></tag>
   <elementGuidId>d487bd5b-776b-401e-b2c4-7e8138d46da4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']//span[contains(text(),'Save')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@type='button']//span[contains(text(),'Save')]</value>
      <webElementGuid>456503e9-c637-497b-99e4-3507294f71fa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
