<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InviteAll_Yes_Button</name>
   <tag></tag>
   <elementGuidId>46faae2e-dc9e-4f56-947c-bd0155e1562b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[normalize-space()='Yes']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[normalize-space()='Yes']</value>
      <webElementGuid>91ddb7b9-c450-4fe4-a5ec-57030ac452b7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
