<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InviteButton_Single_Allteam</name>
   <tag></tag>
   <elementGuidId>7effd606-15b8-4d28-bcba-ba1ad385f7a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/app-root[1]/app-dashboard[1]/div[1]/div[1]/div[2]/app-teammember[1]/div[1]/div[2]/div[2]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[15]/div[1]/button[1]/span[2]/img[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//body[1]/app-root[1]/app-dashboard[1]/div[1]/div[1]/div[2]/app-teammember[1]/div[1]/div[2]/div[2]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[15]/div[1]/button[1]/span[2]/img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/app-root[1]/app-dashboard[1]/div[1]/div[1]/div[2]/app-teammember[1]/div[1]/div[2]/div[2]/mat-tab-group[1]/div[1]/mat-tab-body[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[15]/div[1]/button[1]/span[2]/img[1]</value>
      <webElementGuid>f137301f-9ae4-4ff7-bdeb-32898ff81a67</webElementGuid>
   </webElementProperties>
</WebElementEntity>
