<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search_ListAssign_Partner_StaffTab</name>
   <tag></tag>
   <elementGuidId>6f6b3013-f9b8-4b6d-b421-4baf0e36a49d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@role='menu']//div//div//form//mat-form-field[@floatlabel='always']//div//div//div//input[@placeholder='Search']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
