<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyTotalTeamCount</name>
   <tag></tag>
   <elementGuidId>92a0c728-3972-4812-8ac4-1d6d742b569e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[normalize-space()='10']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h2[normalize-space()='7']</value>
      <webElementGuid>e688db50-f4d8-45f7-9258-fa63b6b8248a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
