<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckboxBesideJE</name>
   <tag></tag>
   <elementGuidId>32ba371d-e1c4-4754-900f-0db0435a36c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-mdc-checkbox-2-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-mdc-checkbox-2-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76f5d315-5fec-4605-8693-d5fb9d1e815c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d46ae5c2-5fa4-4a08-b930-255e3fd328dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-checkbox__native-control</value>
      <webElementGuid>5a1f58de-632d-4953-9d2a-8cd500ee4f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-mdc-checkbox-2-input</value>
      <webElementGuid>f7a59436-400c-4cfb-8d5e-ae55aae91982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>74bfae13-1209-4c9d-bb20-1a8e23eb5630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-checkbox-2-input&quot;)</value>
      <webElementGuid>4ee8b7d4-5067-4f51-bf89-ae3ae4945a5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-mdc-checkbox-2-input']</value>
      <webElementGuid>4f975ffe-2095-4169-9ec8-53b3156f7114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='mat-mdc-checkbox-2']/div/div/input</value>
      <webElementGuid>e07b6990-fba6-4034-aee9-a8e05a7ef7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/mat-checkbox/div/div/input</value>
      <webElementGuid>067757c1-a76a-4735-8fcc-6cd85386c07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mat-mdc-checkbox-2-input']</value>
      <webElementGuid>f2481e92-7e6a-4a9e-8058-7c7894d5899f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
