<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBFrameClick</name>
   <tag></tag>
   <elementGuidId>6b98eefe-edbe-45e9-b16a-4fa4999fcd4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tbGrid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
