<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1234</name>
   <tag></tag>
   <elementGuidId>8acc8452-fe89-400b-b89a-cf6a15bd2ca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tbGrid']/table/tbody/tr[84]/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.mat-mdc-row.mdc-data-table__row.cdk-row.addedtwo.ng-star-inserted > td.mat-mdc-cell.mdc-data-table__cell.cdk-cell.cdk-column-accountcode.mat-column-accountcode.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0de2c51e-194c-4b1c-9bad-e21c7fb26eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-cell mdc-data-table__cell cdk-cell cdk-column-accountcode mat-column-accountcode ng-star-inserted</value>
      <webElementGuid>2c8c6b47-2fa1-417e-aceb-9a483d4d5c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>00eaa204-ff32-4845-a330-1d37282ea7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>1234</value>
      <webElementGuid>c27e7275-db21-40ac-aa0d-325428680f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 1234 </value>
      <webElementGuid>e5b4bd99-5a75-478d-9722-76624b6bd8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbGrid&quot;)/table[@class=&quot;mat-mdc-table mdc-data-table__table cdk-table m-0 table-countable cell-p-8 hover-action trialBalTable customized-sort post-adjusting-selectedrow-color&quot;]/tbody[@class=&quot;mdc-data-table__content&quot;]/tr[@class=&quot;mat-mdc-row mdc-data-table__row cdk-row addedtwo ng-star-inserted&quot;]/td[@class=&quot;mat-mdc-cell mdc-data-table__cell cdk-cell cdk-column-accountcode mat-column-accountcode ng-star-inserted&quot;]</value>
      <webElementGuid>3c475ce1-a1ca-419a-aa1a-34adf374851d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbGrid']/table/tbody/tr[84]/td[3]</value>
      <webElementGuid>76face98-664d-4eec-bb40-d25341a9e9e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD'])[1]/following::td[2]</value>
      <webElementGuid>09611e61-3dc3-421d-ab39-452870888b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NA'])[48]/following::td[5]</value>
      <webElementGuid>29d0c767-d6b9-4b8f-b0b0-36359123a14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test@1234'])[1]/preceding::td[1]</value>
      <webElementGuid>6a23279b-65eb-49a2-ba73-57780dc934eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='H'])[4]/preceding::td[9]</value>
      <webElementGuid>504aad80-52dd-4464-96c5-0fbf62b463f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1234']/parent::*</value>
      <webElementGuid>a083c2e7-8f3d-41c5-8298-37e5daf454f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[84]/td[3]</value>
      <webElementGuid>7cdbdada-e05d-4c6a-ab8d-71c781824bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = '1234' and (text() = ' 1234 ' or . = ' 1234 ')]</value>
      <webElementGuid>53fdd282-cc20-49c5-9ced-ef6f5d111f1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
