<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_test1234</name>
   <tag></tag>
   <elementGuidId>33e9d890-9ed7-433f-b2d8-6a0afa5b1676</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tbGrid']/table/tbody/tr[84]/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.mat-mdc-row.mdc-data-table__row.cdk-row.addedtwo.ng-star-inserted > td.mat-mdc-cell.mdc-data-table__cell.cdk-cell.border-end.cdk-column-accountname.mat-column-accountname.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>bffb9fbe-03a8-4496-afa4-ef7f4143b2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-cell mdc-data-table__cell cdk-cell border-end cdk-column-accountname mat-column-accountname ng-star-inserted</value>
      <webElementGuid>8619c90b-b107-4146-bc6d-f36a1e158964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>45a1fa1d-418a-48fc-acfc-a4a9452a266f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>test@1234</value>
      <webElementGuid>a8f7a047-aa67-47e4-be70-b8633720894f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> test@1234 </value>
      <webElementGuid>8baf3b2c-1455-469f-aa87-a3f40e6652c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbGrid&quot;)/table[@class=&quot;mat-mdc-table mdc-data-table__table cdk-table m-0 table-countable cell-p-8 hover-action trialBalTable customized-sort post-adjusting-selectedrow-color&quot;]/tbody[@class=&quot;mdc-data-table__content&quot;]/tr[@class=&quot;mat-mdc-row mdc-data-table__row cdk-row addedtwo ng-star-inserted&quot;]/td[@class=&quot;mat-mdc-cell mdc-data-table__cell cdk-cell border-end cdk-column-accountname mat-column-accountname ng-star-inserted&quot;]</value>
      <webElementGuid>9126678e-560d-443c-a627-56cf678f4c3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbGrid']/table/tbody/tr[84]/td[4]</value>
      <webElementGuid>49a01899-718f-462b-b1f5-1c34edbad4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD'])[1]/following::td[3]</value>
      <webElementGuid>2d00b84d-3d37-4e0a-9adf-dea5162736a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NA'])[48]/following::td[6]</value>
      <webElementGuid>eaf55993-fe16-43eb-98b0-db8ba3e5719c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='H'])[4]/preceding::td[8]</value>
      <webElementGuid>5a44d7c4-aea0-4783-8380-52f276bcb10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assets'])[78]/preceding::td[9]</value>
      <webElementGuid>f6f18da1-902c-43a3-98cf-10697ec68c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test@1234']/parent::*</value>
      <webElementGuid>2c88335b-2380-479c-bc7d-c7532c49e93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[84]/td[4]</value>
      <webElementGuid>07bce920-7567-44de-8f81-c2091d579483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'test@1234' and (text() = ' test@1234 ' or . = ' test@1234 ')]</value>
      <webElementGuid>e0854224-d927-4d02-82cc-2762418e1c1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
