<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Description filter_list</name>
   <tag></tag>
   <elementGuidId>eba793c6-f08c-470a-86cd-5c851b21723f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tbGrid']/table/thead/tr/th[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.mat-mdc-header-cell.mdc-data-table__header-cell.cdk-header-cell.border-end.cdk-column-accountname.mat-column-accountname.ng-star-inserted.mat-mdc-table-sticky.mat-mdc-table-sticky-border-elem-top</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>3511c995-6872-42ad-8a7f-c715975a9ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>columnheader</value>
      <webElementGuid>c3ec6db7-dd7f-4883-a489-948aa7f37c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-header-cell mdc-data-table__header-cell cdk-header-cell border-end cdk-column-accountname mat-column-accountname ng-star-inserted mat-mdc-table-sticky mat-mdc-table-sticky-border-elem-top</value>
      <webElementGuid>296050ba-b532-422a-ae3f-d493b6f46c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Description filter_list</value>
      <webElementGuid>48fd6f30-8ad7-4088-a218-c82cb6065aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbGrid&quot;)/table[@class=&quot;mat-mdc-table mdc-data-table__table cdk-table m-0 table-countable cell-p-8 hover-action trialBalTable customized-sort post-adjusting-selectedrow-color&quot;]/thead[1]/tr[@class=&quot;mat-mdc-header-row mdc-data-table__header-row cdk-header-row tblheader ng-star-inserted&quot;]/th[@class=&quot;mat-mdc-header-cell mdc-data-table__header-cell cdk-header-cell border-end cdk-column-accountname mat-column-accountname ng-star-inserted mat-mdc-table-sticky mat-mdc-table-sticky-border-elem-top&quot;]</value>
      <webElementGuid>24655312-eb7a-46c1-9d3f-a25f7d05f6c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbGrid']/table/thead/tr/th[4]</value>
      <webElementGuid>38c47f99-6162-4632-8af8-1b1eb47ed8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acc No.'])[1]/following::th[1]</value>
      <webElementGuid>347ed833-6f74-47d2-9ae5-fe91c2a4d239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/following::th[4]</value>
      <webElementGuid>f53b7081-da24-4f38-95cd-3457674f8dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Original'])[1]/preceding::th[1]</value>
      <webElementGuid>aade3cc0-98c9-4906-b4ca-b4cacd9c806d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adj'])[1]/preceding::th[2]</value>
      <webElementGuid>6a939a74-40cc-4dad-83ce-03ebe343d599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Description']/parent::*</value>
      <webElementGuid>f4d6136b-4e26-4efe-a818-5d070b835c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]</value>
      <webElementGuid>d06276e1-98ab-4fd2-99a4-11cd3ac40cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = ' Description filter_list' or . = ' Description filter_list')]</value>
      <webElementGuid>b2f26fe4-568d-4b2a-89db-c028b376987e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
