<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TypeDeactivate_Placeholder</name>
   <tag></tag>
   <elementGuidId>8e88d864-6593-4307-83f6-6175e907388d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Deactivate']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@placeholder='Deactivate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@placeholder='Deactivate']</value>
      <webElementGuid>27d1838d-911f-42c8-8f81-b17576e12126</webElementGuid>
   </webElementProperties>
</WebElementEntity>
