<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>engagemnetPartnerSelectionFirstIValue</name>
   <tag></tag>
   <elementGuidId>c1e127b3-99b0-4434-8474-782d95c29de4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a067b50e3169-0']/div/div/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.mail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3dcc6cdc-33a2-4fbd-b148-05bfd60ecd87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mail</value>
      <webElementGuid>961260f8-6c39-4c20-8af6-2830651297c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>testreg1138@yopmail.com</value>
      <webElementGuid>e3af0075-663a-4ae4-bd29-0f19a945eed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>testreg1138@yopmail.com</value>
      <webElementGuid>0704fcb9-f1eb-4b04-b9b2-303f3ed490cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a067b50e3169-0&quot;)/div[@class=&quot;partner-view user-list-item ng-star-inserted&quot;]/div[@class=&quot;item-content&quot;]/p[@class=&quot;mail&quot;]</value>
      <webElementGuid>8cb38246-162f-4e44-b025-ff3341fa0bd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a067b50e3169-0']/div/div/p[2]</value>
      <webElementGuid>5619cb2a-82eb-423f-ad18-e0337ef4bd62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SA'])[1]/following::p[2]</value>
      <webElementGuid>cc7501d0-9a2f-4a4d-8b38-144e4f90e200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::p[2]</value>
      <webElementGuid>62123604-bc2f-4fc3-8e23-39568fe5fdc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Client Member'])[1]/preceding::p[1]</value>
      <webElementGuid>ddf18f00-1768-47ac-a0f4-2e18a1b16294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[2]/preceding::p[1]</value>
      <webElementGuid>67d19084-e087-42f2-b010-61590c95a640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>d2de4929-26c5-4350-90d0-86080b4d9d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@title = 'testreg1138@yopmail.com' and (text() = 'testreg1138@yopmail.com' or . = 'testreg1138@yopmail.com')]</value>
      <webElementGuid>b0e266c4-9b3b-4f00-b404-93565ac92fc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
