<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__ng-arrow-EngagementPartner</name>
   <tag></tag>
   <elementGuidId>38b02e7e-0176-42b4-89bf-14fd1a205c25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-step-content-0-2']/div/div/div[2]/form/div/div[3]/ng-select/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ng-select.ng-select-searchable.ng-select.ng-select-single.ng-pristine.ng-invalid.ng-select-bottom.ng-touched > div.ng-select-container > span.ng-arrow-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>43fe73d6-ff07-4987-9f23-a4dad746d234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-arrow-wrapper</value>
      <webElementGuid>d6df0297-53ed-4d92-993f-884800bc7fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-step-content-0-2&quot;)/div[@class=&quot;stepper-body-main gap-24 ng-star-inserted&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body gap-24&quot;]/form[@class=&quot;ng-invalid ng-star-inserted ng-touched ng-dirty&quot;]/div[@class=&quot;form-group row-item-4&quot;]/div[@class=&quot;form-item ng-form-field required&quot;]/ng-select[@class=&quot;ng-select-searchable ng-select ng-select-single ng-pristine ng-invalid ng-select-bottom ng-touched&quot;]/div[@class=&quot;ng-select-container&quot;]/span[@class=&quot;ng-arrow-wrapper&quot;]</value>
      <webElementGuid>a67e8b52-6959-4df8-82d0-25055ca4b68c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-0-2']/div/div/div[2]/form/div/div[3]/ng-select/div/span</value>
      <webElementGuid>bb2182bd-3ac9-4269-99b1-d8e3539d1561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::span[1]</value>
      <webElementGuid>545a89c3-abb2-4d0a-aac3-726fc822d6d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Client Member'])[1]/preceding::span[3]</value>
      <webElementGuid>69d0a8c0-03a6-472e-bd88-4523618139b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[2]/preceding::span[7]</value>
      <webElementGuid>0e0069f2-5df7-4edb-8d4a-a72a60606519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ng-select/div/span</value>
      <webElementGuid>343bcba0-72f8-4dc1-bdfc-c1ee14ef9005</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
