<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_Button_Peg_Pact_Licence</name>
   <tag></tag>
   <elementGuidId>46acccf5-3e93-4d4c-b4de-072053c9a171</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-firm-information//span[contains(text(),'Edit')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
