<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Existing_Folder_Drp_List</name>
   <tag></tag>
   <elementGuidId>7c510c3e-c7a6-4f86-8722-fa2734de8971</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body//div//div[@dir='ltr']//mat-form-field[@floatlabel='always']//div//div//div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
