<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClientAddress_ProvienceState</name>
   <tag></tag>
   <elementGuidId>7a0cf43c-01de-49aa-87cd-d04482d4eb63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@formcontrolname='clientState']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@formcontrolname='clientState']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@formcontrolname='clientState']</value>
      <webElementGuid>b241ddf4-85d9-43d3-bbdf-f722e802e878</webElementGuid>
   </webElementProperties>
</WebElementEntity>
