<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClientAddress_PinCode</name>
   <tag></tag>
   <elementGuidId>b72334f0-ad15-40ea-93fb-1033ba225e16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-form-field[14]//div[1]//div[2]//div[1]//input[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[placeholder='Postal/Zip Code']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='s54doc'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//mat-form-field[14]//div[1]//div[2]//div[1]//input[1]</value>
      <webElementGuid>74171bcd-74fe-420c-9797-8d17e99cd48f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
