<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_test1234</name>
   <tag></tag>
   <elementGuidId>b8eee2ab-939d-4607-b245-3a3e19a603af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td[title='test@1234']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tbGrid']/table/tbody/tr[84]/td[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;tbGrid&quot;)/table[@class=&quot;mat-mdc-table mdc-data-table__table cdk-table m-0 table-countable cell-p-8 hover-action trialBalTable customized-sort post-adjusting-selectedrow-color&quot;]/tbody[@class=&quot;mdc-data-table__content&quot;]/tr[@class=&quot;mat-mdc-row mdc-data-table__row cdk-row addedtwo ng-star-inserted&quot;]/td[@class=&quot;mat-mdc-cell mdc-data-table__cell cdk-cell border-end cdk-column-accountname mat-column-accountname ng-star-inserted&quot;][count(. | //td[@class = 'mat-mdc-cell mdc-data-table__cell cdk-cell border-end cdk-column-accountname mat-column-accountname ng-star-inserted' and @role = 'cell' and @title = 'test@1234' and (text() = ' test@1234' or . = ' test@1234')]) = count(//td[@class = 'mat-mdc-cell mdc-data-table__cell cdk-cell border-end cdk-column-accountname mat-column-accountname ng-star-inserted' and @role = 'cell' and @title = 'test@1234' and (text() = ' test@1234' or . = ' test@1234')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;test@1234&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5b44b254-7e00-4891-9148-78f84472382a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-cell mdc-data-table__cell cdk-cell border-end cdk-column-accountname mat-column-accountname ng-star-inserted</value>
      <webElementGuid>6f723500-214d-45e1-a7be-67830bf5d056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>8986c4f5-85e4-48ea-8781-614c2220d35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>test@1234</value>
      <webElementGuid>55a35fad-d4b3-4cf9-a148-c49f7c21d86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> test@1234</value>
      <webElementGuid>c930ad8b-0e31-41af-97e7-cf8b571d9378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbGrid&quot;)/table[@class=&quot;mat-mdc-table mdc-data-table__table cdk-table m-0 table-countable cell-p-8 hover-action trialBalTable customized-sort post-adjusting-selectedrow-color&quot;]/tbody[@class=&quot;mdc-data-table__content&quot;]/tr[@class=&quot;mat-mdc-row mdc-data-table__row cdk-row addedtwo ng-star-inserted&quot;]/td[@class=&quot;mat-mdc-cell mdc-data-table__cell cdk-cell border-end cdk-column-accountname mat-column-accountname ng-star-inserted&quot;]</value>
      <webElementGuid>5874be20-48be-4196-ac19-56c014bd28d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbGrid']/table/tbody/tr[84]/td[4]</value>
      <webElementGuid>b69103a1-40bd-4091-a035-e2aba9211d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD'])[1]/following::td[3]</value>
      <webElementGuid>830e713a-93b1-4d4e-b163-662103aaa3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NA'])[48]/following::td[6]</value>
      <webElementGuid>2ba6bad9-d3d9-406b-bb6a-327232411f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='H'])[4]/preceding::td[8]</value>
      <webElementGuid>f779c82e-e4bd-4649-85f4-83ebff46fac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assets'])[78]/preceding::td[9]</value>
      <webElementGuid>74e43a70-bcdb-43a0-9d5a-17f1a27200a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test@1234']/parent::*</value>
      <webElementGuid>1b049746-106b-4f01-accf-e315a5dbc088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[84]/td[4]</value>
      <webElementGuid>fab7e94b-3a8b-450f-aa75-b83f0e65fe1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'test@1234' and (text() = ' test@1234 ' or . = ' test@1234 ')]</value>
      <webElementGuid>a95e5ea2-7762-478e-8baa-7ff6543077e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
