<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClientSelection_Drp_Dwn_Create_Engmnt</name>
   <tag></tag>
   <elementGuidId>25bcc00f-caf2-4aa8-a362-c3ec2578bb8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@bindvalue='clientfirmid']//span[@class='ng-arrow-wrapper']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
