<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Compilation_TypeTextVerification_BalSheet</name>
   <tag></tag>
   <elementGuidId>e4405d4a-148e-4f7a-8770-318f600acd52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div//div//div//div//div//div//div//div//div//div[1]//ul[1]//li[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
