<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_Button_Status_Clmn</name>
   <tag></tag>
   <elementGuidId>80322ae6-6190-4e15-ae93-96bb57a494db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/app-root[1]/app-dashboard[1]/div[1]/div[1]/div[2]/engagements-list[1]/div[1]/div[2]/engagements-list-grid[1]/div[1]/div[2]/table[1]/thead[1]/tr[1]/th[7]/button[1]/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
