<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Firm_Template_Created_Tax_Dropdwn</name>
   <tag></tag>
   <elementGuidId>ec631f77-7ad9-4bdc-b9d6-017febc8b1ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-panel-title[@title='FirmTemplate_Tax']//img[@alt='Toogle']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
