<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestRun_V31_UAT</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>08c8b58e-96ae-4c35-b57d-efd4da27f03c</testSuiteGuid>
   <testCaseLink>
      <guid>57580738-9cad-4069-89e6-18958ce9ccf9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_UAT_Environment_Scripts/Script3_Add_Signature_To_Frm_User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39810e68-b577-4a80-9d23-12c368870184</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b65e3c17-a452-4629-9066-180e5e29b9f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_UAT_Environment_Scripts/Script4_Add_Firm_Template_All</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbbfa77a-36c3-4466-9d6b-74263673ea45</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b283b2e-1628-4368-befa-2791eba8d10f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_UAT_Environment_Scripts/Script5_Inside_Engagement_LHS_All</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69d74886-abf1-46c2-b92c-79c6aac56788</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>713d2332-4011-4b2f-8f2e-52248ac079e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_UAT_Environment_Scripts/Script6_Inside_Eng_RHS_All</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>315d36fa-002d-4641-8b7a-f6f1a94cda9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25e164b8-cb93-41e5-9811-3c151cbdfafa</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
