<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Delete All_mat-mdc-checkbox-1-input</name>
   <tag></tag>
   <elementGuidId>e3b509c5-0f65-4f22-8122-8fd4eaafb754</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-mdc-checkbox-1-input']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mat-mdc-checkbox-1-input&quot;)[count(. | //input[@type = 'checkbox' and @class = 'mdc-checkbox__native-control' and @id = 'mat-mdc-checkbox-1-input' and @tabindex = '0']) = count(//input[@type = 'checkbox' and @class = 'mdc-checkbox__native-control' and @id = 'mat-mdc-checkbox-1-input' and @tabindex = '0'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-mdc-checkbox-1-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>970a3a70-8024-4c1f-bcea-b2b0caed32cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>025fb61a-2fae-4612-8f97-46c33d87227e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-checkbox__native-control</value>
      <webElementGuid>2448b7e4-b3ce-43c1-99bb-9b6a082c5746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-mdc-checkbox-1-input</value>
      <webElementGuid>aa398751-d879-4fba-b926-541848b87f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5f9b1bd9-c213-40ec-863d-8b803abe26e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-checkbox-1-input&quot;)</value>
      <webElementGuid>3a9ecb64-26e9-4eb4-b4d6-a754070db29b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-mdc-checkbox-1-input']</value>
      <webElementGuid>763ccab4-7451-4e49-8d27-8281d8e24a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='mat-mdc-checkbox-1']/div/div/input</value>
      <webElementGuid>5d64f7d9-88c6-4bca-a76c-1211231b8020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-checkbox/div/div/input</value>
      <webElementGuid>d6cb2320-a95b-4e31-813d-648b876bdaea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mat-mdc-checkbox-1-input']</value>
      <webElementGuid>4be6cfbd-2266-4f9c-98ad-276a0916f25b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
