<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JE2Checkbox</name>
   <tag></tag>
   <elementGuidId>a5da7723-5ffb-444e-b0af-4f295e6729bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-mdc-checkbox-3-input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mat-mdc-checkbox-3-input&quot;)[count(. | //input[@type = 'checkbox' and @class = 'mdc-checkbox__native-control' and @id = 'mat-mdc-checkbox-3-input' and @tabindex = '0']) = count(//input[@type = 'checkbox' and @class = 'mdc-checkbox__native-control' and @id = 'mat-mdc-checkbox-3-input' and @tabindex = '0'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-mdc-checkbox-3-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c67d170-1687-4087-ada4-d711194ed031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>00deffb8-a245-418f-a605-aca50d655e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-checkbox__native-control</value>
      <webElementGuid>5fad0623-3a25-45aa-8ca4-e8ac4a8d50ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-mdc-checkbox-3-input</value>
      <webElementGuid>3c518c5e-c9b1-4faf-a30f-294913a790d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>37304405-bb0d-4d9e-a854-ca0f2e783488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-checkbox-3-input&quot;)</value>
      <webElementGuid>8d8335e5-0a3a-4bb1-acf6-19996956b422</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-mdc-checkbox-3-input']</value>
      <webElementGuid>ab8e0d53-906f-46ff-9b60-2c4315622b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='mat-mdc-checkbox-3']/div/div/input</value>
      <webElementGuid>6c1e3afd-ad63-4d48-9d3e-f7c23c038c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/mat-checkbox/div/div/input</value>
      <webElementGuid>9a64b157-1994-4a67-bd5f-270f153281f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mat-mdc-checkbox-3-input']</value>
      <webElementGuid>05d2ffc7-5932-4b0d-8b4f-fd731277ba34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
