<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBGrouping_Refresh</name>
   <tag></tag>
   <elementGuidId>6fb225de-0e75-4b80-8c87-8abebaff7007</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/app-root[1]/app-trail-balance-working-sheet[1]/div[1]/div[1]/mat-drawer-container[1]/mat-drawer-content[1]/div[1]/app-trial-balance-ls-grouping[1]/div[1]/div[1]/div[1]/button[2]/span[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
