<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TBGrouping_LS_NewLS_LSField</name>
   <tag></tag>
   <elementGuidId>4d14aa2a-0862-4fdb-9eb0-33d7f9643ff3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;LSMAPDialog&quot;]/div[2]/div[2]/ls-dropdown/div/form/div[3]/ng-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
