<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add_Document_Menu_Close_BTN</name>
   <tag></tag>
   <elementGuidId>00a39e32-e43c-49ac-a5d6-5ea845947404</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body//div//div[@dir='ltr']//div//div//div//div//div[1]//button[1]//span[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
