<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CliAceptnceCont_Objective</name>
   <tag></tag>
   <elementGuidId>bfa0c049-cb57-4038-8493-66e5ba1fb184</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body//app-root//client-acceptance//mat-expansion-panel//span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
