<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FileRename_Text_Box_Cli_Accptnc_Continuance</name>
   <tag></tag>
   <elementGuidId>75f036ae-5f7c-49e6-b50e-0eacff849106</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body//div//div[@dir='ltr']//div//div//div//div//div//div[2]//div[1]//input[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
