<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rename_Uploaded_File_Cli_Acc_Contince</name>
   <tag></tag>
   <elementGuidId>eb2d555a-6de6-421e-985a-cf14547c78d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(),'Rename')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//span)[534]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span)[534]</value>
      <webElementGuid>98b79d50-734c-4b38-87d0-ae85cefdb91d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
