<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>scroll_chklist_cliacptcont</name>
   <tag></tag>
   <elementGuidId>5ee1991e-d41b-4bed-902d-4cf71b272e98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/app-root[1]/app-dashboard[1]/div[1]/div[1]/div[2]/ntr-dashboard[1]/div[1]/div[3]/client-acceptance[1]/div[1]/div[2]/div[1]/div[1]/div[5]/div[2]/mat-form-field[1]/div[1]/div[1]/div[1]/textarea[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
