<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Notes</name>
   <tag></tag>
   <elementGuidId>529ca540-475f-4072-a977-5b84399efc73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body//div//div//table[@role='table']//thead[@role='rowgroup']//tr[@role='row']//th[@role='columnheader']//mat-checkbox//div//div//input[@type='checkbox']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
