<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Uploaded_File_Client_Accep_Continuance</name>
   <tag></tag>
   <elementGuidId>a89f282e-3298-4ff6-82b2-f39aeb403fd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root/app-dashboard/div/div/div/ntr-dashboard/div/div/div/div/mat-accordion[@multi='true']/mat-expansion-panel/div[@role='region']/div/mat-expansion-panel/div[@role='region']/div/ul/li/div[@title='CA-1-RenamedFile.xlsx']/span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//span)[76]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span)[76]</value>
      <webElementGuid>b5fd0cf4-2788-47bb-b3f7-14168ead8aa9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
