<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>759d148d-9270-4a1d-915f-469837b9ea48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='adobe-dc-view']/div/div/div/div/div/button[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.spectrum-Button.spectrum-Button--primary.sdk-SaveActionView-save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e1d4ecb-ffa6-47f2-853e-1c6edbdea43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>spectrum-Button spectrum-Button--primary sdk-SaveActionView-save</value>
      <webElementGuid>ced0b90c-8266-4c4c-8d9f-f624d43cf6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>b2bc5315-61d8-42b0-a2bd-630edfa6da9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adobe-dc-view&quot;)/div[@class=&quot;JuTe6q_spectrum _5QszkG_spectrum _5QszkG_i18nFontFamily PFjRbG_spectrum--light xSyFOq_spectrum--medium zA6MfG_spectrum zA6MfG_spectrum--dark zA6MfG_spectrum--darkest zA6MfG_spectrum--large zA6MfG_spectrum--light zA6MfG_spectrum--lightest zA6MfG_spectrum--medium&quot;]/div[@class=&quot;react-spectrum-provider spectrum spectrum--light spectrum--medium&quot;]/div[@class=&quot;MainApp__app___d1GrX&quot;]/div[1]/div[@class=&quot;sdk-HeaderView-header sdk-HeaderView-header-modernViewer&quot;]/button[@class=&quot;spectrum-Button spectrum-Button--primary sdk-SaveActionView-save&quot;]</value>
      <webElementGuid>07a98de6-d362-46a5-98f8-45b70a96ba02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/trypdfedit/iframe_Close edit mode_iframe-pdf_div</value>
      <webElementGuid>33cf6487-6ae3-4083-b7ec-1a73c9b3cd39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adobe-dc-view']/div/div/div/div/div/button[3]</value>
      <webElementGuid>0ddf6048-465d-481c-a19d-23cccd1e5d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 1'])[1]/preceding::button[7]</value>
      <webElementGuid>2ee3e2e3-d409-4bf4-8918-f358772dc448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>e329e2c1-dd6b-4722-88d2-20e3a255661b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>50813b4e-00c2-44a1-9397-b244e4bd6aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>fbeefd70-2c62-4529-ab4f-f2d3debf3e8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
