<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save_verb-comment-stickynote</name>
   <tag></tag>
   <elementGuidId>7fb99e1b-183a-4537-83e1-249d76da903f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='verb-comment-stickynote']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#verb-comment-stickynote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9285d6f7-3d5b-47ff-a3fc-8056674d9292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verb-comment-stickynote</value>
      <webElementGuid>40a6dadf-99ee-4136-9bda-8693b98bcf3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>38b95943-eb1b-40a5-a7f7-fb099afb8dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add comments</value>
      <webElementGuid>b97bbc91-7470-4710-978c-f71843068b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>825d1bc6-5d54-4400-b061-28a463e0aeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>spectrum-ActionButton spectrum-ActionButton--quiet</value>
      <webElementGuid>7b347368-207e-4f6c-846d-fbb7d62e37dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verb-comment-stickynote&quot;)</value>
      <webElementGuid>c80f77da-7156-4ef6-b7e4-99fe488367b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/trypdfedit/iframe_Close edit mode_iframe-pdf_div</value>
      <webElementGuid>978b8712-31ab-45ff-b110-1b65655923c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='verb-comment-stickynote']</value>
      <webElementGuid>30818ba4-81c6-43d3-aa3e-02db02ab8877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quick-tools-view']/ul/li[2]/div/div/div/button</value>
      <webElementGuid>eb53bc4c-bcf0-4e26-9834-de0f4f4137c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::button[4]</value>
      <webElementGuid>20e84159-6b4c-4787-9a80-edf333f0b86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 1'])[1]/preceding::button[3]</value>
      <webElementGuid>76dab7ed-9dc5-48c9-8cb0-a7f0d8c13129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/button</value>
      <webElementGuid>887539bc-9677-4107-8ceb-1fe1a3f76afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'verb-comment-stickynote']</value>
      <webElementGuid>1c859f41-4356-4c4e-b846-958ddebc56cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
