<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save_preview-select</name>
   <tag></tag>
   <elementGuidId>b1f964c9-e35b-4a1a-b2f8-c05495b67261</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='preview-select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#preview-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e6ec945-0c06-4ac2-bcdf-3c28f82c659d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preview-select</value>
      <webElementGuid>b9db825c-528d-4f28-88b1-83ff095e4b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f8ee4ace-44b6-454b-a0f0-ecda90d60007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Use select tool</value>
      <webElementGuid>8fd3363f-9938-4240-b8eb-f5804b6619f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9c659c09-0d47-4edc-844e-c78e5b5b88b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>spectrum-ActionButton spectrum-ActionButton--quiet</value>
      <webElementGuid>22f4b98e-fd08-46f7-9f4c-8db5b4ebccbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preview-select&quot;)</value>
      <webElementGuid>61b93844-a9c3-4eca-8185-9ef972c030d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/trypdfedit/iframe_Close edit mode_iframe-pdf_div</value>
      <webElementGuid>eb43c8f3-3bf8-48b6-8a1c-c8c5c503692f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='preview-select']</value>
      <webElementGuid>bbac4dd7-e1f1-426e-ab11-c61eea280105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quick-tools-view']/ul/li/div/div/div/button</value>
      <webElementGuid>b5e7e0c8-1229-4ad5-a9e7-fb296e792be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::button[3]</value>
      <webElementGuid>4196bfda-915f-4f51-bf34-1782e693c734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 1'])[1]/preceding::button[4]</value>
      <webElementGuid>cc611518-7921-4b07-ba8d-4a920b8fce2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test entity'])[1]/preceding::button[4]</value>
      <webElementGuid>650edb25-e865-499f-a601-732e0cd1dd50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/button</value>
      <webElementGuid>99e564a7-ad2e-4465-b0e4-e8cabebc23fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'preview-select']</value>
      <webElementGuid>2ac2f74c-bf4d-4f1f-a8fa-f211753c78b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
