<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add comments</name>
   <tag></tag>
   <elementGuidId>a811eca1-f158-4b13-a02a-4b08e7c204da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-spectrum-63']/div/div/div/div/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.FlyoutTabItem__Label___3Kc6o</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>13963084-9c96-4ce8-97a9-72372f5fa003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FlyoutTabItem__Label___3Kc6o</value>
      <webElementGuid>3219fd4b-2002-4645-a02d-c3642cd12f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add comments</value>
      <webElementGuid>a3b2188d-2307-418c-8152-468b518a69bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-spectrum-63&quot;)/div[1]/div[@class=&quot;Flyout__FlyoutTabList___1g0gU&quot;]/div[1]/div[1]/div[@class=&quot;FlyoutTabItem__TabItem___AqYc_&quot;]/div[@class=&quot;FlyoutTabItem__iconAndLabel___2Ezww&quot;]/div[@class=&quot;FlyoutTabItem__LabelDiv___QJTEZ&quot;]/div[@class=&quot;FlyoutTabItem__Label___3Kc6o&quot;]</value>
      <webElementGuid>1e0c0995-34ea-4081-9c77-69d652f45ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/trypdfedit/iframe_Close edit mode_iframe-pdf_div</value>
      <webElementGuid>cf524a9f-465e-4acd-bfe1-1cc076ef124a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-spectrum-63']/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>56c63d8d-d98a-490e-ad7a-00cd8768bfbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[35]</value>
      <webElementGuid>d8eb3218-edb4-443f-a640-427b0e5f48f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add text comment'])[1]/preceding::div[3]</value>
      <webElementGuid>b198a28e-a071-41af-9654-f8560bb9f243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 1'])[1]/preceding::div[25]</value>
      <webElementGuid>d6a043c1-bc6c-443a-9a96-532925cc34a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add comments']/parent::*</value>
      <webElementGuid>37678de9-1e0e-4e09-b89b-354d4e327b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div[3]/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>e7da00ba-ff3f-428b-8b85-9de909e0c276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Add comments' or . = 'Add comments')]</value>
      <webElementGuid>6e57f85e-15f6-4435-aae1-b6d0136a8e55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
