<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_comments)_CommentsView__commentsHighlig_ff0a70</name>
   <tag></tag>
   <elementGuidId>00663b08-27d2-4aff-8871-12891c087cd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pageview-current-page']/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.CommentsView__commentsHighlight___BDn6U</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cdf02a04-34b3-4060-9ee1-15c5b73ae78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CommentsView__commentsHighlight___BDn6U</value>
      <webElementGuid>92c0e93a-2946-44f4-b0c5-edde565820ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pageview-current-page&quot;)/div[@class=&quot;PageCanvas__overlayClass___2fbb8&quot;]/div[@class=&quot;PageCanvas__overlayComponentContainer___3VZrA PageCanvas__fullPageGeometry___1QVxf&quot;]/div[1]/div[1]/div[@class=&quot;commentsOverlay&quot;]/div[@class=&quot;CommentsView__commentsHighlight___BDn6U&quot;]</value>
      <webElementGuid>20a7b75e-a7d8-453d-b1f1-3769339fb743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/trypdfedit/iframe_Close edit mode_iframe-pdf_div</value>
      <webElementGuid>52b835f9-dbb7-4e0a-843c-07ca66252ca2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageview-current-page']/div/div/div/div/div/div</value>
      <webElementGuid>9d7b728d-5370-4b5f-9d38-bc2e404abc45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[3]/div/div/div/div/div/div</value>
      <webElementGuid>0de7e97f-240e-4448-bf16-563bc098a69d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
