<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Close edit mode_iframe-pdf_div</name>
   <tag></tag>
   <elementGuidId>fc5113cf-0f3a-426b-ac95-1c6e46f33034</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframe-pdf_div']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframe-pdf_div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b09f79fd-18cf-4dc6-ba54-c1c02aad8913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://documentservices.adobe.com/view-sdk/3.27.1_3.2.4-b4b0ecd5/iframe.html?locale=en-US&amp;msi=11210010295100105118&amp;parent=https%3A%2F%2Fuat.adinovis.com%2Ffile-preview%2Fpdf%2Ffalse%2F8dfe5a29-78e9-4864-b5c8-9e05837466ef%2Fedit</value>
      <webElementGuid>ccc19c56-8646-4b8a-9dce-e9e88aaffedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframe-pdf_div</value>
      <webElementGuid>e54adfdc-2e7a-423e-872d-2b83fd8bbb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>allowfullscreen</value>
      <webElementGuid>a966e5f7-75e6-4520-b3ab-e0206aed0729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PDF Embed API</value>
      <webElementGuid>c7a0ccfc-eb65-408c-8474-a11d00f37745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframe-pdf_div&quot;)</value>
      <webElementGuid>149795c8-0736-4260-be49-8d24b27b5513</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframe-pdf_div']</value>
      <webElementGuid>3a5e0ee2-e211-4725-b606-aef881c425b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdf_div']/iframe</value>
      <webElementGuid>7f356224-0c98-4c4a-86e1-a9f0c1db7628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>492fdd27-7544-44df-b869-774ed5e15be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://documentservices.adobe.com/view-sdk/3.27.1_3.2.4-b4b0ecd5/iframe.html?locale=en-US&amp;msi=11210010295100105118&amp;parent=https%3A%2F%2Fuat.adinovis.com%2Ffile-preview%2Fpdf%2Ffalse%2F8dfe5a29-78e9-4864-b5c8-9e05837466ef%2Fedit' and @id = 'iframe-pdf_div' and @title = 'PDF Embed API']</value>
      <webElementGuid>95f8df2a-a09d-43ce-8444-21d50235781c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
