<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Post</name>
   <tag></tag>
   <elementGuidId>d4e0570e-220b-4e4b-9d00-937b4a7757bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a193b525-2ee3-8713-60h1-9bc8baafaac']/table/tbody/tr/td[2]/div/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.spectrum-ActionButton-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cec47661-d49c-4909-9e41-9c181210847b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>spectrum-ActionButton-label</value>
      <webElementGuid>0b69765c-daa8-49b7-8cdb-68af7efa02c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Post</value>
      <webElementGuid>00821fa5-46e3-4aa6-aae5-0f4be25d6ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-spectrum-104&quot;)/div[1]/div[@id=&quot;a193b525-2ee3-8713-60h1-9bc8baafaac&quot;]/div[1]/div[@class=&quot;CommentPopup__modernCommentExpandedItemContainer___SsF1Q&quot;]/div[2]/div[1]/div[@id=&quot;a193b525-2ee3-8713-60h1-9bc8baafaac&quot;]/table[@class=&quot;ModernEditableTextComponent__ModernToolsContainer___gqMK8&quot;]/tbody[1]/tr[@class=&quot;ModernEditableTextComponent__ModernDisplayButtons___IPoQ2&quot;]/td[@class=&quot;ModernEditableTextComponent__ModernPostTool___fRhg8&quot;]/div[1]/div[1]/button[@class=&quot;spectrum-ActionButton spectrum-ActionButton--quiet ModernEditableTextComponent__PostToolText___AYHrj&quot;]/span[@class=&quot;spectrum-ActionButton-label&quot;]</value>
      <webElementGuid>9d098bde-0355-46ab-b750-222fec3b4d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/trypdfedit/iframe_Close edit mode_iframe-pdf_div</value>
      <webElementGuid>fcc7c60f-ec98-42a4-9e5b-8634fed88c5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a193b525-2ee3-8713-60h1-9bc8baafaac']/table/tbody/tr/td[2]/div/div/button/span</value>
      <webElementGuid>49fca697-43db-435e-9a07-d858ebdf718a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='abcsssdfdf'])[1]/following::span[1]</value>
      <webElementGuid>a2f0d578-44f6-431e-95bf-0a1fd9563b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='just now'])[1]/following::span[1]</value>
      <webElementGuid>23184073-9ba5-4328-8a7f-39e54d38f010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[1]</value>
      <webElementGuid>c5d81d41-ab84-4f1f-a3ea-423685b728d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CD'])[2]/preceding::span[2]</value>
      <webElementGuid>b67518d4-602a-48fc-bc6b-713062936924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Post']/parent::*</value>
      <webElementGuid>eaecab0a-652a-496c-b47f-cd061ce6627d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/span</value>
      <webElementGuid>50f6efca-d800-46d3-8440-5f10e4afe8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Post' or . = 'Post')]</value>
      <webElementGuid>1b898140-ee08-4630-aaa9-dbdf1dcdb289</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
