<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EngagementPeriod</name>
   <tag></tag>
   <elementGuidId>3e3d2485-d7d7-4628-885b-23fc2969c954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='MM/DD/YYYY']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@placeholder='MM/DD/YYYY']</value>
      <webElementGuid>2f192a45-a845-477b-bd4b-fcbb3cf46c50</webElementGuid>
   </webElementProperties>
</WebElementEntity>
