<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectClientArrowbutton</name>
   <tag></tag>
   <elementGuidId>f1af91cc-8109-4f58-8cc7-5695deca8c54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='ng-arrow-wrapper']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@class='ng-arrow-wrapper']</value>
      <webElementGuid>6f9dfd24-5dff-4c0c-a7c2-6300b832311b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
