<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_EDITADJ</name>
   <tag></tag>
   <elementGuidId>dc0319df-16f2-4988-b5b4-ec41b22d6d34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='icon'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button-small-icon.edit-btn.mdc-button.mat-mdc-button.mat-unthemed.mat-mdc-button-base.ng-star-inserted.cdk-focused.cdk-mouse-focused > span.mdc-button__label > img[alt=&quot;icon&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5658ceb1-f654-4213-9356-4ceb86031c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ngsrc</name>
      <type>Main</type>
      <value>/assets/images/ui-uplift-icons/global/edit-pencile-Icon.svg</value>
      <webElementGuid>05e17162-3a79-432a-aaa5-57ecd3355f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>b6ab8971-6190-4230-94e3-786eeab1ba1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>8dc4242f-c8f5-4ca7-804d-73e2cf7a911a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>f63641dd-24cf-4e73-aea9-1c869ed02b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>526d508f-087c-48c5-93f4-9b724190c069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c283780a-f04f-4b90-b614-a8df7aa340a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-img</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f04bf0a6-ef4d-4e51-82cd-55b19aa0b16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/ui-uplift-icons/global/edit-pencile-Icon.svg</value>
      <webElementGuid>f6fa48fe-a49c-43bc-8381-cc074df9e51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-adj-entry[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page-wraper adjustment-active&quot;]/div[@class=&quot;content-block-main p-0 h-100 overflow-hidden&quot;]/div[@class=&quot;d-flex flex-row h-100 overflow-hidden&quot;]/div[@class=&quot;content-block-main border-top gap-20 pt-4 adjustment-entriess h-100 overflow-hidden&quot;]/div[@class=&quot;adjustment-entries-body h-100 overflow-auto ng-star-inserted&quot;]/div[@class=&quot;horizontal-items&quot;]/div[@class=&quot;card ng-star-inserted&quot;]/div[@class=&quot;card-header min-h-auto px-3&quot;]/div[@class=&quot;button-group gap-4 justify-content-end ng-star-inserted&quot;]/button[@class=&quot;button-small-icon edit-btn mdc-button mat-mdc-button mat-unthemed mat-mdc-button-base ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mdc-button__label&quot;]/img[1]</value>
      <webElementGuid>2f7daedd-b501-49bf-87e9-ff5d087a0a10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[6]</value>
      <webElementGuid>c034801a-2003-4074-993f-acf5b18fa0c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span[2]/img</value>
      <webElementGuid>49fb6d19-7a81-4ce0-be03-93eb3b42aeba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'icon' and @src = '/assets/images/ui-uplift-icons/global/edit-pencile-Icon.svg']</value>
      <webElementGuid>070e0395-e3a2-4024-a18c-b17391b9ebf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
