<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_delete_mat-mdc-button-touch-target_DELETE_CONFIRMATION</name>
   <tag></tag>
   <elementGuidId>6ddbae4c-daf2-4b19-9fb4-9675ce49bf60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[2]/span[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button-small.mdc-button.mat-mdc-button.mdc-button--unelevated.mat-mdc-unelevated-button.mat-error.mat-mdc-button-base.ng-star-inserted.cdk-focused.cdk-mouse-focused > span.mat-mdc-button-touch-target</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c0868f3d-6283-4b96-bb34-49cedd67d2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-button-touch-target</value>
      <webElementGuid>333967b9-2115-41db-b03c-feda9fb32001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-adj-entry[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page-wraper adjustment-active&quot;]/div[@class=&quot;content-block-main p-0 h-100 overflow-hidden&quot;]/div[@class=&quot;vertical-items justify-content-between px-4 py-3&quot;]/div[@class=&quot;custom-row flx-left delete-content ng-star-inserted&quot;]/div[@class=&quot;toast-container w-100 position-static&quot;]/div[@class=&quot;ngx-toastr toast-error w-100&quot;]/div[@class=&quot;toast-message d-flex flex-row align-items-center&quot;]/div[@class=&quot;button-group&quot;]/button[@class=&quot;button-small mdc-button mat-mdc-button mdc-button--unelevated mat-mdc-unelevated-button mat-error mat-mdc-button-base ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-mdc-button-touch-target&quot;]</value>
      <webElementGuid>3083d335-d83c-48bd-a6ae-afb1b3228a5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span[4]</value>
      <webElementGuid>a1152fc8-1864-40a1-8180-d70e69bfe313</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
