<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Eliminating</name>
   <tag></tag>
   <elementGuidId>3141d39e-9809-4b76-bfff-84ebebf56e39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(.,'Eliminating')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a3ead8b7b377-1 > span.ng-option-label.ng-star-inserted</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Eliminating' or . = 'Eliminating')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>119bb373-8f33-483a-80b2-820d6057fc1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option-label ng-star-inserted</value>
      <webElementGuid>0b3bc449-63a9-4dd8-a7b5-1bfc9aa58909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eliminating</value>
      <webElementGuid>2bf498ae-2ed0-4a26-af36-a6f23817e0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a3ead8b7b377-1&quot;)/span[@class=&quot;ng-option-label ng-star-inserted&quot;]</value>
      <webElementGuid>163b14da-4417-465d-97a7-a9fdf97cb0dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[contains(.,'Eliminating')]</value>
      <webElementGuid>13ae5acc-777d-46dd-b15a-0771ec7015c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Journal'])[2]/following::span[1]</value>
      <webElementGuid>c21ae38f-f8e4-489b-9cd2-eb172064cb08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Journal'])[1]/following::span[4]</value>
      <webElementGuid>d0e5c55f-96cd-42f9-8ee9-95b4e7734747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PBC'])[1]/preceding::span[1]</value>
      <webElementGuid>694d39b4-b304-4739-859b-e0495bc2d259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reclassifying Journal Entry'])[1]/preceding::span[2]</value>
      <webElementGuid>83f94679-a5f0-42fb-97a0-25c1653016f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eliminating']/parent::*</value>
      <webElementGuid>feab5998-2444-4787-856d-c65b68b2885c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span</value>
      <webElementGuid>afa84f89-fa84-44ed-8c4b-bb40adf01650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Eliminating' or . = 'Eliminating')]</value>
      <webElementGuid>aea417a8-e785-4e80-a048-3b3bb69b9ca5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
