<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_No</name>
   <tag></tag>
   <elementGuidId>a9736c6c-b2aa-4b60-9e2d-89b8b3ffda8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a2860e3f4c73-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='ng-option-label ng-star-inserted'][normalize-space()='No']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'a2860e3f4c73-1' and (text() = 'No' or . = 'No')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>36487b29-fac6-45e5-966e-e2d508a14840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>f4c67d96-757c-4990-8565-cc3220244a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cb8f4e20-3b34-434e-a9c2-7a96a80d0514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d881052-f8d7-4dad-9cde-8ba85dfb8621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a2860e3f4c73-1</value>
      <webElementGuid>99cbb483-6ef4-4b7d-8e87-55d29525db7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>87815ca4-b0ee-45a0-bd47-283f7c12e14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a2860e3f4c73-1&quot;)</value>
      <webElementGuid>066d401f-36d9-4601-a85f-f37a4afee2a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@class='ng-option-label ng-star-inserted'][normalize-space()='No']</value>
      <webElementGuid>41797eac-4a04-4cea-a5e8-826d7e53e267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a2860e3f4c73']/div/div[2]/div[2]</value>
      <webElementGuid>a5a07b5f-c4e1-4a73-b594-c6f2a6dafe4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::div[1]</value>
      <webElementGuid>456346fe-90c1-44e0-9e76-35c9c993a465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[6]</value>
      <webElementGuid>6e901fc6-fd97-42ed-9365-44e374464d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Point of Contact'])[1]/preceding::div[1]</value>
      <webElementGuid>31578789-c96b-4b6b-b400-0cf03ea09c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[2]</value>
      <webElementGuid>029866ff-23d8-4108-8048-461dd361e7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a2860e3f4c73-1' and (text() = 'No' or . = 'No')]</value>
      <webElementGuid>e3f3b857-4ee4-4468-9eb2-a4a9a46112c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
