<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Corporation</name>
   <tag></tag>
   <elementGuidId>e5b103b2-6c02-4e1d-bb0b-bea8c2e17ca9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a8f31ae9df97-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@title='Corporation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a15440d4-cb1e-4895-b84f-04ee21322912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-selected ng-option-marked ng-star-inserted</value>
      <webElementGuid>e45bbbc1-c431-4035-a1ec-c07a348ac3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d624c379-2468-4c12-a3f6-7aaa44e88f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a0040f51-a0f0-46b3-a8b5-b7b7c1d9cfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a8f31ae9df97-0</value>
      <webElementGuid>acb8525b-c2af-4100-a54d-7f1c85914e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Corporation</value>
      <webElementGuid>617bf0b7-fc90-4dfc-bef5-39033983ebdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a8f31ae9df97-0&quot;)</value>
      <webElementGuid>8497acae-ef69-44f5-9abe-3563ecdbf0a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@title='Corporation']</value>
      <webElementGuid>7f5fc7f0-83fc-4744-a95b-f74bef0abe56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a8f31ae9df97']/div/div[2]/div</value>
      <webElementGuid>635b3561-914b-45ae-82f6-49cecb566ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporation'])[1]/following::div[5]</value>
      <webElementGuid>fb9658ee-7583-4327-9c5a-2d6003c4a298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::div[6]</value>
      <webElementGuid>7ab7c361-1516-4cd5-9db1-2699c7eb1f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[2]/preceding::div[3]</value>
      <webElementGuid>1d647588-097d-4ad4-9dc1-2257d02c0443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>6bc5d9a0-6eee-4f4e-b8e0-7ee294ff2961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a8f31ae9df97-0' and (text() = 'Corporation' or . = 'Corporation')]</value>
      <webElementGuid>3ad1d267-47c2-492f-a3bd-5629a3433fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a99a820854da-0']</value>
      <webElementGuid>f60e4767-2732-4143-af21-1240b10dd166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a99a820854da']/div/div[2]/div</value>
      <webElementGuid>1191bd93-40a4-4151-853b-59b79609ebc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::div[5]</value>
      <webElementGuid>29f5f3ed-e5bc-4c4a-bf62-94a87d2236be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a99a820854da-0' and (text() = 'Corporation' or . = 'Corporation')]</value>
      <webElementGuid>68f06f55-1a8d-4738-9e4a-cd778005e807</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
