<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Firm NameAddressCityProvinceStateCount_a38690</name>
   <tag></tag>
   <elementGuidId>42e79c5f-2bd2-4ae2-8674-80c7519d062a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.card-body.gap-24.ng-invalid.ng-dirty.ng-touched</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-step-content-0-0']/div/form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>4663ea60-6479-4e0c-9746-112f9dd1af5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1f618fc2-25a1-42d6-938f-f954928b0fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body gap-24 ng-invalid ng-dirty ng-touched</value>
      <webElementGuid>85b24e45-7a08-4b38-8bba-b6dbee68aa6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Firm NameAddressCityProvince/StateCountryPostal/Zip CodePEG/PACT Subscriber*Select*Point of ContactMember IDLicense NoFirst NameLast NameBusiness PhoneCell PhoneEmailHourly RateTitle Go to Step 2 keyboard_arrow_right</value>
      <webElementGuid>a165ec1f-01af-4e8a-ae5a-4373fb080722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-step-content-0-0&quot;)/div[@class=&quot;stepper-body-main card ng-star-inserted&quot;]/form[@class=&quot;card-body gap-24 ng-invalid ng-dirty ng-touched&quot;]</value>
      <webElementGuid>865fd16a-78eb-43b5-8861-f10bcbeb7af2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-0-0']/div/form</value>
      <webElementGuid>7966cb3c-4071-4dc2-9534-a22e8757c2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 1 : Account Information'])[1]/following::form[1]</value>
      <webElementGuid>d4d81b2b-217e-4dbf-937a-a20e096e1d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 4: Invite Team'])[1]/following::form[1]</value>
      <webElementGuid>e07dd8f9-b888-4b62-b6cf-8ecdc9a7f052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>67646851-ea23-4aaa-976f-6fd40e93847c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'Firm NameAddressCityProvince/StateCountryPostal/Zip CodePEG/PACT Subscriber*Select*Point of ContactMember IDLicense NoFirst NameLast NameBusiness PhoneCell PhoneEmailHourly RateTitle Go to Step 2 keyboard_arrow_right' or . = 'Firm NameAddressCityProvince/StateCountryPostal/Zip CodePEG/PACT Subscriber*Select*Point of ContactMember IDLicense NoFirst NameLast NameBusiness PhoneCell PhoneEmailHourly RateTitle Go to Step 2 keyboard_arrow_right')]</value>
      <webElementGuid>79bfbe1f-6bc2-4b7f-b2a8-6e256bcaa122</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
