<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_staff_r_btn_addTeam</name>
   <tag></tag>
   <elementGuidId>542ed8ee-750e-4d83-8a55-71f1911f7ebf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-radio-9-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-radio-9-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d158f2f9-9575-4a8b-aa5e-fa4c0a543d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8df99d98-bbf5-4b3d-bd57-2cec6cd58b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-radio__native-control</value>
      <webElementGuid>bdda060e-703d-4d4f-b53f-75c224c441fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-radio-9-input</value>
      <webElementGuid>de56feff-c04a-457f-987c-c41a4fc45618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mat-radio-group-6</value>
      <webElementGuid>d3a87f8d-b7c2-43b0-a52c-2debbe6783c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>72ae5020-4925-4eaa-b608-ab37fee06643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>391be421-3a09-42cd-921b-514edc9c4e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-radio-9-input&quot;)</value>
      <webElementGuid>f15ddf6e-d3e2-4538-a8c8-8ef8c2764e6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-radio-9-input']</value>
      <webElementGuid>efe2708c-c754-4e13-b67e-af1a978c68fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-radio-button[@id='mat-radio-9']/div/div/input</value>
      <webElementGuid>a81b811f-a837-4464-b5cf-67e67c6d85ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/mat-radio-group/mat-radio-button[2]/div/div/input</value>
      <webElementGuid>4de97dc3-f640-480d-886b-0584ef0176b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'mat-radio-9-input' and @name = 'mat-radio-group-6']</value>
      <webElementGuid>1aed8670-60ad-426e-8971-0c00da5b95a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
