<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_mat-input-1_1</name>
   <tag></tag>
   <elementGuidId>c0f47985-d66f-44cb-b30a-8760f30bf0b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-input-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c8e3eaa-1867-4731-a041-7263f78383bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c0d3da12-bc8c-47a0-ac44-971fe78a8372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c791a5be-5aef-4163-9fa3-f5d03c3d1d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>262ea258-daf7-4a14-bc85-ac3a117d29d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-input-element ng-tns-c1798928316-2 ng-untouched ng-pristine ng-invalid mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored</value>
      <webElementGuid>39ff43b9-aa4a-464a-955e-c1aec3b1986c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-1</value>
      <webElementGuid>f2548db8-92ec-40b7-b208-6873dc712a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>756da551-8fc1-4350-a47b-69a4ed1f41b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>154e6614-3b29-458d-b7bc-6a58e5a9b751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-1&quot;)</value>
      <webElementGuid>2d4ff3c8-6109-49cd-93c7-618259e66aa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-1']</value>
      <webElementGuid>9db1834f-96e0-4425-9767-f6ed90d7f413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[2]/div/div[2]/div/input</value>
      <webElementGuid>fc43bf15-1a61-4fcc-be6e-80303c7d5a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password' and @id = 'mat-input-1']</value>
      <webElementGuid>6b9f8429-832b-4487-9942-b13c7b95eba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Password' and @id = 'mat-input-1']</value>
      <webElementGuid>b9a94070-c6f7-4815-868b-157f212ddb2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
