<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ng-arrow-wrapper_access_type_addteam</name>
   <tag></tag>
   <elementGuidId>d41b16b3-2338-40f1-8c4d-dc5a41b12db5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@class='ng-arrow-wrapper'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-group.row-items-4 > div.form-item.ng-form-field > ng-select.ng-select-searchable.ng-select.ng-select-single.ng-untouched.ng-pristine.ng-valid > div.ng-select-container.ng-has-value > span.ng-arrow-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>686d53b4-8505-40a0-b9b7-4ee25108352d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-arrow-wrapper</value>
      <webElementGuid>81c3d1d8-a8e5-4297-adb6-98597021bd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-step-content-0-1&quot;)/div[@class=&quot;stepper-body-main gap-24 ng-star-inserted&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body gap-24&quot;]/div[@class=&quot;upload-table fm-importpreview-table addnew-section ng-star-inserted&quot;]/div[@class=&quot;form-lavel mt-lg-4 mt-3 ng-star-inserted&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;form-group row-items-4&quot;]/div[@class=&quot;form-item ng-form-field&quot;]/ng-select[@class=&quot;ng-select-searchable ng-select ng-select-single ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;ng-select-container ng-has-value&quot;]/span[@class=&quot;ng-arrow-wrapper&quot;]</value>
      <webElementGuid>2c349dac-c0f9-419b-9fde-a411383543fa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
