<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ng-arrow_entity_type_addClient</name>
   <tag></tag>
   <elementGuidId>0e60b66e-b85c-4f27-9dc2-33c9ea4f1778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@placeholder='Entity Type']//span[@class='ng-arrow-wrapper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ng-select.ng-select-searchable.ng-select.ng-select-single.ng-pristine.ng-invalid.ng-select-focused.ng-select-bottom.ng-touched > div.ng-select-container > span.ng-arrow-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>37c0195b-38b2-49de-b5cd-ae8050e9e4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-arrow-wrapper</value>
      <webElementGuid>3291e4a3-c24e-43ca-81d4-73bf6d7ece2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-step-content-0-2&quot;)/div[@class=&quot;stepper-body-main gap-24 ng-star-inserted&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body gap-24&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-star-inserted ng-touched&quot;]/div[@class=&quot;form-group row-item-4&quot;]/div[@class=&quot;form-item ng-form-field&quot;]/ng-select[@class=&quot;ng-select-searchable ng-select ng-select-single ng-pristine ng-invalid ng-select-focused ng-select-bottom ng-touched&quot;]/div[@class=&quot;ng-select-container&quot;]/span[@class=&quot;ng-arrow-wrapper&quot;]</value>
      <webElementGuid>ae2928fc-6542-44e4-a8b5-43ec9f28374e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-0-2']/div/div/div[2]/form/div/div/ng-select/div/span</value>
      <webElementGuid>651b46f8-1988-4ae1-bab3-c23326aa53de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::span[1]</value>
      <webElementGuid>48b351a4-449d-40b0-a6ad-b250e81ef79f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[2]/preceding::span[2]</value>
      <webElementGuid>aa7faf2d-3b55-474a-aa1b-33ff1a739994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[2]/preceding::span[3]</value>
      <webElementGuid>a2c77e98-3c24-4a4e-80ee-e67875d0ed01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div/ng-select/div/span</value>
      <webElementGuid>cdb4e3aa-263d-431e-9769-52e9217a4aca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
