<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_testreg1120yopmail.com</name>
   <tag></tag>
   <elementGuidId>079c5edb-61b2-48c6-bc2d-a52518a26438</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.mail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aefd7371958c-0']/div/div/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>682e0333-779e-44b4-a584-34e18035857d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mail</value>
      <webElementGuid>cdc76869-5317-433c-b13a-776e426b6c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>testreg1120@yopmail.com</value>
      <webElementGuid>3346eafa-8130-4754-8856-54dfe34f3348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>testreg1120@yopmail.com</value>
      <webElementGuid>1b03ddc7-6137-4852-b889-07da30062ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aefd7371958c-0&quot;)/div[@class=&quot;partner-view user-list-item ng-star-inserted&quot;]/div[@class=&quot;item-content&quot;]/p[@class=&quot;mail&quot;]</value>
      <webElementGuid>676645d4-fae8-40a8-86c9-e38a761a0987</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aefd7371958c-0']/div/div/p[2]</value>
      <webElementGuid>e2eb6930-ddeb-4b38-8a3f-3dbae0d14ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SA'])[1]/following::p[2]</value>
      <webElementGuid>bfdce806-dd42-4527-8388-8355979d99ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::p[2]</value>
      <webElementGuid>9cf46a59-1d9b-4677-ab5d-43fcfed9f969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SK'])[1]/preceding::p[1]</value>
      <webElementGuid>766a18ab-22bd-4f8f-b1fc-acee8754a284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Client Member'])[1]/preceding::p[3]</value>
      <webElementGuid>972a431f-d24d-46ed-b5da-31350da1dae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>ebe76ad4-a0b3-43b6-b749-f2422f36d3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@title = 'testreg1120@yopmail.com' and (text() = 'testreg1120@yopmail.com' or . = 'testreg1120@yopmail.com')]</value>
      <webElementGuid>ab239e88-03cf-4ef8-aeaa-d1352878049b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
