<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectionEng_Partner_Suraj Agnihotry</name>
   <tag></tag>
   <elementGuidId>29446dff-2d47-40e7-964c-4e5339663f19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@class='name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>24c7be7a-4ef6-40b5-b269-eb4c66a6818c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>e86769eb-00c6-41fe-bd31-7a6d1d07185a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Suraj Agnihotry</value>
      <webElementGuid>cd3206e9-31c7-423f-84b1-be9ba739a01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suraj Agnihotry</value>
      <webElementGuid>6d3dedd9-9fe1-43ec-85f8-52397b4d79e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ad09c52be4a2-0&quot;)/div[@class=&quot;partner-view user-list-item ng-star-inserted&quot;]/div[@class=&quot;item-content&quot;]/p[@class=&quot;name&quot;]</value>
      <webElementGuid>d850f4e0-074a-48af-98af-0094dbe4ed09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@class='name']</value>
      <webElementGuid>cab60644-ce2e-4872-95ab-4300fcccd141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SA'])[1]/following::p[1]</value>
      <webElementGuid>e05e158b-f49e-4909-97fb-0f76aea88b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::p[1]</value>
      <webElementGuid>ddfe5672-721d-4fbe-a0e1-73f1dcc91e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AH'])[1]/preceding::p[2]</value>
      <webElementGuid>1c64454d-d51e-477c-bc8d-c3327023dd71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Client Member'])[1]/preceding::p[4]</value>
      <webElementGuid>a04e2668-3f5c-428e-8fd7-0c0f1ba9a32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/p</value>
      <webElementGuid>d650c4c8-6a54-4e52-ae59-c9d0e7cdae9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@title = 'Suraj Agnihotry' and (text() = 'Suraj Agnihotry' or . = 'Suraj Agnihotry')]</value>
      <webElementGuid>2b9fd249-40a5-4ef9-bc23-f60ac0df4800</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
