<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LSFilterHover</name>
   <tag></tag>
   <elementGuidId>3e5fb29f-101c-4a58-ab93-c1f2c3050f71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[contains(.,'LS')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
