<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_JE-1</name>
   <tag></tag>
   <elementGuidId>f585a21e-1e9f-4b74-96ac-f3b5936183e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-menu-panel-72']/div/div[2]/table/tbody/tr/td/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.text-ellipse.text-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9c3df43f-5fac-44fe-b4bf-efe5eb4ef4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-ellipse text-link</value>
      <webElementGuid>8d585871-b616-4da6-ae6a-c1915a20c5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JE-1</value>
      <webElementGuid>266cb002-1d8b-46b9-98db-f5ac247c331f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-72&quot;)/div[@class=&quot;mat-mdc-menu-content ng-tns-c681116372-798&quot;]/div[@class=&quot;adj-table ng-star-inserted ng-tns-c681116372-798&quot;]/table[@class=&quot;mat-mdc-table mdc-data-table__table cdk-table table-countable&quot;]/tbody[@class=&quot;mdc-data-table__content&quot;]/tr[@class=&quot;mat-mdc-row mdc-data-table__row cdk-row ng-star-inserted&quot;]/td[@class=&quot;mat-mdc-cell mdc-data-table__cell cdk-cell cursor-pointer cdk-column-entryno mat-column-entryno ng-star-inserted&quot;]/span[@class=&quot;text-ellipse text-link&quot;]</value>
      <webElementGuid>64e1d31d-a380-4217-b4a3-097c2310462c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-72']/div/div[2]/table/tbody/tr/td/span</value>
      <webElementGuid>3f4b4e76-eb1c-4e00-a40a-029fe6ce8848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::span[1]</value>
      <webElementGuid>ecfa2b9f-dd24-4e19-b4d2-9f030c153134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REF'])[1]/following::span[1]</value>
      <webElementGuid>6fe4ff4c-a96b-4ab9-8765-ca169718be38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::span[5]</value>
      <webElementGuid>7ea0b1a1-29a2-4828-8c83-d79a01cbdd22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JE-1']/parent::*</value>
      <webElementGuid>90abe5d1-7493-414c-833b-dcd9e96c089a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/span</value>
      <webElementGuid>05227579-51eb-4a4b-9da5-7759f2dd7f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'JE-1' or . = 'JE-1')]</value>
      <webElementGuid>74769887-08e1-4660-9cf1-d269c5068511</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
