<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-</name>
   <tag></tag>
   <elementGuidId>2595fddd-7eeb-4420-87ab-3788bcf916fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body > app-root:nth-child(1) > app-dashboard:nth-child(2) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > ntr-dashboard:nth-child(2) > div:nth-child(1) > div:nth-child(3) > trailbalance-details:nth-child(4) > div:nth-child(1) > div:nth-child(2) > div:nth-child(3) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(86) > td:nth-child(11) > button:nth-child(1) > span:nth-child(2) > span:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@title='-']//span//span[contains(text(),'-')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;tbGrid&quot;)/table[@class=&quot;mat-mdc-table mdc-data-table__table cdk-table m-0 table-countable cell-p-8 hover-action trialBalTable customized-sort post-adjusting-selectedrow-color&quot;]/tbody[@class=&quot;mdc-data-table__content&quot;]/tr[@class=&quot;mat-mdc-row mdc-data-table__row cdk-row ng-star-inserted rowSelectColor&quot;]/td[@class=&quot;mat-mdc-cell mdc-data-table__cell cdk-cell mapno cdk-column-mapno mat-column-mapno ng-star-inserted&quot;]/button[@class=&quot;mat-mdc-menu-trigger button-text text-left h-100 w-100 mdc-button mat-mdc-button active active-dropdown mat-unthemed mat-mdc-button-base ng-star-inserted flex-box cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mdc-button__label&quot;]/span[@class=&quot;button-label&quot;][count(. | //span[@class = 'button-label' and (text() = ' - ' or . = ' - ')]) = count(//span[@class = 'button-label' and (text() = ' - ' or . = ' - ')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;-&quot;s] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ee579bc7-f56f-4d04-91e6-1dc9300a6406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-label</value>
      <webElementGuid>0a1f6c6a-fb6b-4bc9-8429-4ad54a331a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> - </value>
      <webElementGuid>762402a8-626c-4f9f-bdd2-f8a2a9a630ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbGrid&quot;)/table[@class=&quot;mat-mdc-table mdc-data-table__table cdk-table m-0 table-countable cell-p-8 hover-action trialBalTable customized-sort post-adjusting-selectedrow-color&quot;]/tbody[@class=&quot;mdc-data-table__content&quot;]/tr[@class=&quot;mat-mdc-row mdc-data-table__row cdk-row ng-star-inserted rowSelectColor&quot;]/td[@class=&quot;mat-mdc-cell mdc-data-table__cell cdk-cell mapno cdk-column-mapno mat-column-mapno ng-star-inserted&quot;]/button[@class=&quot;mat-mdc-menu-trigger button-text text-left h-100 w-100 mdc-button mat-mdc-button active active-dropdown mat-unthemed mat-mdc-button-base ng-star-inserted flex-box cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mdc-button__label&quot;]/span[@class=&quot;button-label&quot;]</value>
      <webElementGuid>634393b6-95b0-4ce8-b7d5-ad01dc9b5840</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@title='-']//span//span[contains(text(),'-')]	</value>
      <webElementGuid>4d26a80c-2fc9-4f47-95ca-88f6796bae2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::span[3]</value>
      <webElementGuid>f1360a43-75f6-49ef-8293-fb63c98b11f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acc No.'])[2]/following::span[3]</value>
      <webElementGuid>b1528256-dc85-4ca4-a0c2-599c914f5875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/preceding::span[4]</value>
      <webElementGuid>2e7f3e2e-06c8-43f3-8ed0-0944e13eac43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[3]/preceding::span[5]</value>
      <webElementGuid>707c3f22-b097-446a-9f07-a6b27be70fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='-']/parent::*</value>
      <webElementGuid>d8136114-915e-43ba-add7-5bd5b15ada98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[82]/td[11]/button/span[2]/span</value>
      <webElementGuid>0634b4d9-fdab-4fe4-ae86-13a009da8a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' - ' or . = ' - ')]</value>
      <webElementGuid>1ab6e3e8-6aa5-4812-9307-004e2a843e1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
